### ISSUE TITLE
Out of memory error uploading file

### ISSUE THREAD

**Issue by ian6868** [nftstorage/nft.storage#1065]
Trying to add a video that's 5.2GBs and getting an out of memory error after uploading for 5 seconds. Tried several times, always the same problem. Any help would be appreciated.

**Comment by dchoi27** [comment]
Hey can you provide more information on how you're trying to upload the file? Via browser, JS client library, etc.

Currently, the entire file needs to be put into memory (and overall memory utilization will be >2x that of the file size) because a CAR file version of the file needs to be generated on the user's side before uploads start. Further, if you're trying to upload via browser, the browser sets memory utilization limits that are lower than the system's limits. We're working on making a more robust upload flow under the hood to expand the users that can upload large files and directories (#980)!

**Comment by dchoi27** [comment]
Yeah, definitely - I'd look into tools like https://github.com/web3-storage/ipfs-car !
