### ISSUE TITLE
Buildout of nft.storage stats page

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#1074]
Design Pending as of 1/29/22.  The actual metric stats needed are set and building out the retrieval of this data addressed in #1193 
This ticket is for the buildout of the designed page, pulling data from whatever means built in 1193. 

We will not be adding this page into top nav as a nav option.  Instead, we'll look for places on homepage or elsewhere to link to this route.  

- [ ] Build page per designs in figma
- [ ]  add "Stats" and link to the new stats page into the site footer
- [ ] consider and recommend where in existing site we can place page link for this 
      - (one suggestion was possibly in the homepage Trusted By section as some new validation link).  
      - (we wil be adding it to footer here https://github.com/nftstorage/nft.storage/issues/1295)

**Comment by JeffLowe** [comment]
JChris reviewing stats design and providing feedback in the figma mock.  awaiting those comments before finalizing and building out.

**Comment by dchoi27** [comment]
So we no longer have to do graphs, we can just have the stats listed @JeffLowe @alanshaw. Submitted a design issue for the PL design team to help out with the design.

Otherwise, the stats that we want are defined in the root issue in #750, and we can start exploring the best way to get those numbers (maybe worth splitting this portion into a different issue @JeffLowe ). 

We have https://api.nft.storage/metrics for total uploads today, and we have some API endpoint to get total data in Filecoin from dagcargo (can just ask in the team channel). 

Alternatively, we can potentially just grab these metrics from Grafana directly (though if Grafana goes down, which it does kind of often, then we have an outage on the stats page). This also makes it easier to calculate W/W changes in numbers rather than rewriting the stats APIs to provide this info.

Existing logos on the homepage can be used to start the logo wall.
