### ISSUE TITLE
Updates to /files page surrounding urls and copy functions

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#1160]
- [x] Remove “URL” and its copy button
- [x] Leave the CID's copy button as it (updating tooltip copy to capitalize "CID")
- [x] hyperlink the CID with the gateway URL
- [x] Add menu to end of row final column, menu should contain:
  - "View" (The Gateway Link, when clicked just loads the link for user to see)
  - "Copy IPFS URI"
  - "Copy CID"
  - "Delete"
- [x] move the "DELETE" option into the menu

This aligns better with what's seen in ipfs UI, aligns with Alan's and David's  recent recs, aligns with draft LFU design, and gives room to add more functionality in menu down the road.

**Comment by JeffLowe** [comment]
@alanshaw What do you think of the above as immediate approach?  This is in addition to the updates called out in #1110,  #1152, and #1144.
And, would replace #1145

**Comment by alanshaw** [comment]
My gut instinct is that if there's going to be more complex UI element like a menu then it should apply to the whole row, include the "delete" operation and be at the end (where the delete button is now). The reason I avoided suggesting it in https://github.com/nftstorage/nft.storage/pull/1085#issuecomment-1016340526 is because it adds another click when copying a CID. So with this change, any time you want to copy any CID, it's a 2 step operation.

I'd actually quite like to put the delete button in a menu to avoid accidental clicks. What if we:

1. Leave the copy icon where it is for quick access to copy a CID
2. Keep the menu idea, but put it where the delete button is now.
3. Keep menu items as defined above but with the addition of delete item at the end

Suggestion for the future perhaps - I've previously worked on UI's where we just have a checkbox, and clicking on it opens a toast at the bottom of the screen. The advantage of this is that it cleans up the table a little, provides lots of space for controls and also opens the door for operations that can be done on multiple items. e.g.

<img width="1178" alt="Screenshot 2022-01-25 at 15 53 44" src="https://user-images.githubusercontent.com/152863/151011217-43fd3a7f-a39b-4657-b84c-a53181b1db3f.png">

**Comment by alanshaw** [comment]
❤️ SGTM
