### ISSUE TITLE
ParseError: /node_modules/nft.storage/src/carbites/treewalk.js

### ISSUE THREAD

**Issue by huweihong** [nftstorage/nft.storage#1169]
When I imported nft.storage in a svelte routify project, I got the following error:

```
ParseError: /node_modules/nft.storage/src/carbites/treewalk.js
Error: ENOENT: no such file or directory, open '/frontend/node_modules/nft.storage/src/carbites/treewalk.js'
    at compileModule (/frontend/node_modules/nollup/lib/impl/NollupCompiler.js:116:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async compileModule (/frontend/node_modules/nollup/lib/impl/NollupCompiler.js:114:13)
    at async compileModule (/frontend/node_modules/nollup/lib/impl/NollupCompiler.js:114:13)
    at async compileModule (/frontend/node_modules/nollup/lib/impl/NollupCompiler.js:114:13)
    at async compileInputTarget (/frontend/node_modules/nollup/lib/impl/NollupCompiler.js:138:5)
    at async Object.compile (/frontend/node_modules/nollup/lib/impl/NollupCompiler.js:235:31)
    at async generateImpl (/frontend/node_modules/nollup/lib/index.js:13:21)
```

the file is not existing in node_module, after checking the node_module. what is this file for? and how to resolve it?

my env: ts + svelte + routify.

thanks.

**Comment by yusefnapora** [comment]
@huweihong, thanks for the report. I haven't used ts + svelte personally so I'm not sure what's up exactly. The `treewalk.js` file doesn't actually exist in the `nft.storage` package - it's from the `carbites` module, which nft.storage depends on.

I notice you're using nollup - can you try with rollup as well and see if you get the same error? Just a guess that the bundler might be involved, since it seems to be a module resolution problem.

Thanks :)

**Comment by vasco-santos** [comment]
Hello @huweihong 

We use a feature of package json called exports to map paths to where the source files are. https://github.com/nftstorage/carbites/blob/main/package.json#L52

In this case, you seem to be using and environment that does not support it. It seems to exist since https://nodejs.org/api/packages.html#exports . So as @yusefnapora mentioned, this is likely related to your bundler.  https://github.com/rollup/plugins/issues/208

**Comment by alanshaw** [comment]
Not sure what was going on here. This seems to be working for me in this example project: https://github.com/alanshaw/svelte-restify-nftstorage-example

(I [added `NFTStorage` class to the window](https://github.com/alanshaw/svelte-restify-nftstorage-example/blob/main/src/pages/index.svelte#L8) and then used it from the console)

<img width="958" alt="Screenshot 2022-02-28 at 15 14 13" src="https://user-images.githubusercontent.com/152863/156007812-96bd83a8-4359-48ac-adf2-aca3460b8d94.png">

**Comment by mondyfy** [comment]
Had a similar issue in ts, fixed after upgrading ts-node and jest(for testing) to the latest version.
