### ISSUE TITLE
Build out means of retrieving data to drive the nft.storage /stats page

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#1193]
nft.storage needs a stats page.  The final design for UI is forthcoming, but the actual stats are specifed, thus we can start identifying/building the means to retrieve the data (the scope of this issue).

We have https://api.nft.storage/metrics for total uploads today, and we have some API endpoint to get total data in Filecoin from dagcargo (can just ask in the team channel for more details). 

The stats that we want are defined in the root issue in #750  ( and listed below) .  

## Needed Stats (adjusted based on design)
- Total number of uploads (with week over week growth rate)
- Total amount of data in Filecoin deals, (with the week over week growth rate)

**Comment by dashcraft** [comment]
@dchoi27 @JeffLowe for
Total number of uploads (with week over week growth rate)
Total amount of data in Filecoin deals, (with the week over week growth rate)

Do we want this to be specifically a 7 day rolling window, or an actual week 02/13-02/19
aggregate?

**Comment by dchoi27** [comment]
It would be `(num_uploads_now - num_uploads_7daysago) / num_uploads_7daysago`. So just the % growth since last week. I'd expect the API to be pulling new numbers at least daily (could be hourly or every 5 min or whatever - don't really mind) but just to keep things flexible, let's just make sure that we're always comparing to the data point 7 days ago.

**Comment by JeffLowe** [comment]
May need to update cron to write total size in metrics table @dashcraft

**Comment by JeffLowe** [comment]
Daniel syncing with Alan on backend blocker
