### ISSUE TITLE
read and write ipfs via smart contract

### ISSUE THREAD

**Issue by genus1** [nftstorage/nft.storage#1379]
I want to send/receive data in JSON format.
Your service appears to do that no problem like the NFT type.

I am looking for a current blockchain with smart contract ability to read the IPFS data and compute and send back new IPFS data.

I do not want to use Ethereum but maybe Solana.

I would like to use NFTStorage with s smart contract to do that but after reviewing many blockchains, I have not found one that will work.

Can  you point me in the right direction or do  you have code with a smart contract to do this?

As example:  Read a CID stored in the contract, import the data for number of apples from IPFS, reduce the numer of apples in the contract, recreate the data with less apples, create a CID to replace in the contract store, then save the new data to the ipfs CID.

I am working on my own code since I have not found any solutions.

Thanks in advance.

**Comment by yusefnapora** [comment]
Unfortunately, reading and writing data from any external system (including IPFS) from a smart contract is a fairly complex problem. The main issue is that the smart contract code will potentially be executed many times, on many different machines, each with different connectivity to the external world. So it's not really possible to write a contract that makes a network request, since there's no way to guarantee that it will return the same result on every node that runs the contract transaction. Even with a system like IPFS where a request for the same CID should always return the same data, there's no way to guarantee that peers will be available on the network to provide the data for every blockchain node that needs it.

It is possible to use an "oracle", which is a service that writes data from the outside world into a known location on-chain in response to an on-chain request. There's a [blog post from Chainlink](https://blog.chain.link/fetch-ipfs-api-data-token-distribution/) about using IPFS via an oracle on the Ethereum VM. I imagine you could use something similar on Solana, but I'm not aware of anything ready made.

Alternatively, you can effectively make your own oracle by writing an off-chain service that does the "read CID -> manipulate data -> write CID" logic, and have that service write the end result CID into the chain. Or if your contract is producing data that needs to be made available on IPFS, your service could poll for contract events and send the result to nft.storage or web3.storage.

Hope that helps! I'm going to close this issue, but feel free to open a new one if you have more question.
