### ISSUE TITLE
Gateway Grafana metrics changes

### ISSUE THREAD

**Issue by alanshaw** [nftstorage/nft.storage#1407]
🙏🙏🙏

- [x] Add descriptive _short_ titles to all graphs
- [x] Add clarifying help text with longer description (if necessary)
- [x] Add labels to all keys
- [x] Join "null values" so graphs can be read more easily
- [x] Fix "no data" for rate limit graphs
- [ ] Friendly units for "content length" graph

**Comment by vasco-santos** [comment]
@alanshaw Did a new iteration in Grafana. Still need to add new diagrams once PRs related to https://github.com/nftstorage/nft.storage/issues/1183 make it in.

>  Fix "no data" for rate limit graphs

the no data in there is due to not having any rate limit hits yet. So, in the metrics page we have:

```
nftgateway_requests_by_status_total{gateway="https://ipfs.io",env="production",status="200"} 429
nftgateway_requests_by_status_total{gateway="https://ipfs.io",env="production",status="404"} 66
nftgateway_requests_by_status_total{gateway="https://cf-ipfs.com",env="production",status="200"} 473
nftgateway_requests_by_status_total{gateway="https://cf-ipfs.com",env="production",status="403"} 7
nftgateway_requests_by_status_total{gateway="https://cf-ipfs.com",env="production",status="404"} 70
nftgateway_requests_by_status_total{gateway="https://nft-storage.mypinata.cloud/",env="production",status="200"} 464
nftgateway_requests_by_status_total{gateway="https://nft-storage.mypinata.cloud/",env="production",status="404"} 85
```

Once we have a `status="429"` error, or in case of prevented a `reason="RATE_LIMIT"` they will show up. The only option would be to initiate the metrics object with these hardcoded and have their value 0... Keeping the rest of the keys dynamic, but I would much rather not do this kind of code changes just to show up in Grafana.

@alanshaw Let me know what you think?

**Comment by vasco-santos** [comment]
> Friendly units for "content length" graph

@alanshaw as far as I can tell, I can't in any way transform the "le" label from bytes to whatever other unit. It is possible to change values, but not labels. Either we change the label value (and have inconsistency between accumulated bytes metrics), or we will have to use bytes in Grafana. What do you think?
