### ISSUE TITLE
Pinning my files through IPFS desktop

### ISSUE THREAD

**Issue by YOGAPAARTIBAN** [nftstorage/nft.storage#1673]
To the attached screenshot, I liked to know what had to be entered in the corresponding fields if I want to pin it to NFT storage.
![yTAzmcfSqn-1](https://user-images.githubusercontent.com/59327023/159187363-130b746c-e02d-4cdf-b109-b98dd73b0531.png)

**Comment by M1lfsh4k3** [comment]
Did you manage to get it done right? Im trying the same way too but no luck.

**Comment by alanshaw** [comment]
You just need `https://api.nft.storage` and your API token.

Then head over here https://github.com/nftstorage/nft.storage/issues/new/choose and click on the last option to get authorized to use the service.

**Comment by M1lfsh4k3** [comment]
Got authorization now, and ofcourse encountered something messy again... 
So I pinned a folder of 25GB and it started uploading and i could see that the uprate went to approx. 1,5mbps at average for a while. After some time it dropped to 0 by the look on the chart and sometimes gets to 500kbps and drops repeatedly, like its connecting and dropping. It says "Hosting 9,2GiB of data" on the top of the status page, does that mean its done with 9.2GB or 9.2 of the 25GB left to host? How do I find the problem here? Ill attach some images of the pin status, folder and bandwidth chart. Thanks in advance, really appreciate all the help you've done so far <3
![3](https://user-images.githubusercontent.com/100882557/159580086-c649b8ad-da13-469b-96bd-144150344760.png)
![4](https://user-images.githubusercontent.com/100882557/159580090-86d198c2-b8c0-4652-ab49-a69119ae2a84.png)
![1](https://user-images.githubusercontent.com/100882557/159580093-e66cc14e-b3c8-4eab-b4bd-145e494ce47b.png)
![2](https://user-images.githubusercontent.com/100882557/159580097-bfd27409-5ff8-454f-b493-188ae19fae20.png)

**Comment by M1lfsh4k3** [comment]
Left it over night on and still not finished or even close, and no uprate at all... 
![image](https://user-images.githubusercontent.com/100882557/159641213-94984940-c25e-4680-89e4-5d3d87a74f55.png)

**Comment by alanshaw** [comment]
How did you get the data into your local IPFS? Someone sent you a CID and you pinned it or did you use `ipfs add` or the webui to add the data?

9.2GB is how much data is in your repo locally.

Can you see the CID you pinned in your files list on the nft.storage website? If you can share it I can look into the current state.

**Comment by alanshaw** [comment]
P.S. probably best to open an new issue for this if the CID does not show as pinned on your file listing on nft.storage.

**Comment by M1lfsh4k3** [comment]
It was only the two CIDs earlier but for some reason it added a third (the highlighted one) today when i messed around in IPFS Desktop.
![image](https://user-images.githubusercontent.com/100882557/159750814-cf9aa50a-d1ff-4e82-a67b-592e62c9a26c.png)
I think because i clicked on "Local pin" aswell, it created a CID with both those folders in it:
![image](https://user-images.githubusercontent.com/100882557/159750971-fd06de45-a6c2-470a-a7f4-0729d4483b73.png)

I added the folders through the Desktop app, "+import" and added them there. Then i used the pinning service to get them to NFT.Storage.

**Comment by M1lfsh4k3** [comment]
@alanshaw sorry the CIDs are:
QmNt4Md96ND5yEMXPiM7HeuAazg55394nDYDUV5GGU41hb
QmWfRK92JiN7rny26YEUTrnNtoZS39zhWMX6UutbWrLcXP

**Comment by YOGAPAARTIBAN** [comment]
Hi All,
I'm getting this message and it still remains in the same status (failed).

**Comment by YOGAPAARTIBAN** [comment]
Till now whatever did been placed here as screenshot. Please troubleshoot and  find a solution[
![B7FtHlTc8R](https://user-images.githubusercontent.com/59327023/159990036-a580076a-7f93-4743-9073-917190a3ea46.png)
![Screen_Recorder24744_7eRujO9qWW](https://user-images.githubusercontent.com/59327023/159990074-d3e3c4f5-86be-4e26-964b-b8386170803f.png)
![Screen_Recorder83056_LXBchdYeBU](https://user-images.githubusercontent.com/59327023/159990093-258d357a-288f-431f-a5e2-171acf9fe72a.png)
![Screenshot_20220324-032126](https://user-images.githubusercontent.com/59327023/159990096-a977e825-2d71-436c-b3c0-7d97917100b9.png)
![Screenshot_20220324-032256](https://user-images.githubusercontent.com/59327023/159990102-a0b4192e-543b-4e2b-8ac2-340c1c7ce819.png)
](url)
