### ISSUE TITLE
Module not found: Error: Can't resolve 'process/browser' when using create-react-app 5

### ISSUE THREAD

**Issue by bassmoneynft** [nftstorage/nft.storage#1706]
I'm using `react 17.0.2` (`create-react-app 5.0.0`) with `react-app-rewired` to polyfill because of Webpack 5 change. `npm 8.3.1` and `node 16.14.0`.

I have tried `npm install process` but that didn't do anything.

These are the steps to reproduce:

1. `npm install --save @nftstorage/metaplex-auth`
2. Add `import { NFTStorageMetaplexor } from '@nftstorage/metaplex-auth';` to my react component.
3. Run `npm start`

Full error:
```
ERROR in ./node_modules/@nftstorage/metaplex-auth/dist/index.browser.js 11112:38-45
Module not found: Error: Can't resolve 'process/browser' in 'node_modules/@nftstorage/metaplex-auth/dist'
Did you mean 'browser.js'?
BREAKING CHANGE: The request 'process/browser' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

**Comment by alanshaw** [comment]
I've just used CRA 5 to create a new project and imported `@nftstorage/metaplex-auth` successfully. I'm using the same npm/node/react versions as you are.

I'm not using `react-app-rewired` though...why do you need this? I'd recommend simply not using it.

The only other thing I can think of is that you mentioned webpack 5 - you DO need to be using webpack 5 to use the NFT.Storage/Metaplex class so if you're using webpack 4 then maybe that's why it's not working?
