### ISSUE TITLE
Phishing attack on Phantom wallet flagged by Chorme, Need help to analyze

### ISSUE THREAD

**Issue by gnanavelum** [nftstorage/nft.storage#1715]
Hi, I have accessed a website(FFF - foxes federation) using Phantom wallet on Chrome, and somehow it injected a bad content/token into my wallet. and the content seems to be sticky with my wallet, as i am able to repro this by restoring my wallet on another brandnew chrome in new machine.

attached the warning i get, let me know how to go about doing anything with this issue.

**Comment by dchoi27** [comment]
Hey - Google blocked nftstorage.link for a few hours with this warning. It should be all cleared now. Can you check to see if this error persists?

**Comment by vasco-santos** [comment]
Ping @gnanavelum 🙏🏼  Do you still have any issues here?

**Comment by day13th** [comment]
<img width="759" alt="SOL_WALLETT" src="https://user-images.githubusercontent.com/107642848/174134027-e5e4b4a4-960c-46f3-8c38-13f2f728a3dc.png">

what can I do with?

**Comment by dchoi27** [comment]
@day13th thanks for reporting. what anti virus software is that? we need more information than that screenshot - it looks like you're accessing it in brave browser - please provide all the details you can!

**Comment by day13th** [comment]
Hallo!

I have this problem around for 2 weeks,  I  have Brave browser , but if i
open the phantom  wallet in  chrome,  the same  problem  apply.

What can  I do?  How to remove?

I have  on the laptop Kaspersky Internet Security

David Choi ***@***.***> ezt írta (időpont: 2022. jún. 16.,
Cs, 20:02):

**Comment by dchoi27** [comment]
According to here, https://opentip.kaspersky.com/https%3A%2F%2Fnftstorage.link%2F/
Kaspersky views the domain as alright. What this probably means is that it's flagging your specific NFT as a false positive. I submitted a report to ask them to look at it, but you should do the same by contacting them here: https://support.kaspersky.com/us/b2c/US#contacts

I'll let you know what they tell me, but again, since it's probably specific to your NFT you should reach out as well.

**Comment by dchoi27** [comment]
@day13th i took this URL from your screenshot https://bafybeihvwepemi7eeglvg6gum7anjntmebjwaspcjyzdtizqrmzla4hava.ipfs.nftstorage.link/metadata.json
but looks like other URLs are being flagged. Can you share them all?

I did reach out to Kaspersky and they apologized. They have this URL at least (https://bafybeihvwepemi7eeglvg6gum7anjntmebjwaspcjyzdtizqrmzla4hava.ipfs.nftstorage.link/metadata.json) and will email me back with updates.

Since you are an actual user of Kaspersky, it's probably best if you also reach out to them still!

**Comment by day13th** [comment]
Hi! 

Thanks a lot, i will do that. 

Az iPhone-omról küldve

**Comment by day13th** [comment]
Yes sure you can share them, if you need any further info let me know! 

Thx a lot

Az iPhone-omról küldve

**Comment by dchoi27** [comment]
@day13th sorry to clarify, i don't have the URLs (just have one ) and need for you to share them (and any additional screenshots) here.

**Comment by day13th** [comment]
Ok  i will do when i m home again, thank a lot. 

Az iPhone-omról küldve

**Comment by dchoi27** [comment]
^ bump @day13th
