### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by Princej646** [nftstorage/nft.storage#1876]
I have tried logging in multiple times but unable to login

**Comment by dchoi27** [comment]
Can you give more details on what you're facing? Do you use email or Github auth? What do you see in practice?

**Comment by uma-studio** [comment]
I'm having problems signing up! Click on confirmation email, go back to original sign up window, it changes to loading animation but then goes no further.

**Comment by alanshaw** [comment]
@Princej646 sometimes the login email doesn't arrive immediately. If that happens and you try to login again, the delayed email might arrive, but it'll be expired (because another is on the way). You can keep doing this - clicking on a delayed (and expired) email and then trying to login again and you'll never be able to login!

If you're having this issue then the best thing to do is just wait a while after your login link arrives in your inbox and you'll likely receive another one that hasn't expired - this is the one you should click on.

@uma-studio I think I've seen this before, do you get stuck on the black spinner on a white screen and nothing else?

**Comment by vrde** [comment]
I also had troubles today logging in via the magic link. Sometimes it works, sometimes it doesn't and it loads forever.
