### ISSUE TITLE
Login error loop

### ISSUE THREAD

**Issue by NFT-PLAYMATE** [nftstorage/nft.storage#1912]
Login then check email. In browser, Click link and it says expired 20sec later, back to login,  repeatedly 

Other attempts, login , check email, on external app, link takes back to login screen...repeatedly

**Comment by alanshaw** [comment]
Sometimes the login email doesn't arrive immediately. If that happens and you try to login again, the delayed email might arrive, but it'll be expired (because another is on the way). You can keep doing this - clicking on a delayed (and expired) email and then trying to login again and you'll never be able to login!

If you're having this issue then the best thing to do is just wait a while after your login link arrives in your inbox and you'll likely receive another one that hasn't expired - this is the one you should click on.

**Comment by dchoi27** [comment]
Closing this for now - let us know if you're pretty confident this isn't the issue!
