### ISSUE TITLE
Allow migration of upload history from one user account to another

### ISSUE THREAD

**Issue by yusefnapora** [nftstorage/nft.storage#1950]
We want to support transferring the upload history from one account to another. 

Possible use cases are when the original account is no longer accessible, or potentially converting from a Github/oauth login to an email-based login (although this probably requires other changes as well).

Decisions to make:
- should API keys be migrated to the new user also?
- what's our policy for allowing this kind of migration?
  - e.g. how can the user verify that they are the authorized user for the original account?
- should we expose this feature through the admin interface? 
  - might be tricky, since it involves a database migration.

**Comment by vasco-santos** [comment]
Thanks for putting this together @yusefnapora . This is a good idea, I think we shouldn't delete affected rows, nor change primary/foreign keys in the process, so, totally "copy rows" ✅ .

I think copy function should also take care of copying `user_tag` and `auth_keys` optionally. SQL function can receive option to wether do it or not, which would be provided by admin when doing the migration.

There are things we need to still consider/discuss here, specially concerned about the authentication/authorization part. We have two different angles here:
- when we copy, the previous user would still be able to see files, as well as have same auth keys. Either we would need to extend tags to have a tag that completely blocks the user, or we can just add a column in `user` table `deleted_at` and change our auth functions to filter out deleted users. I think second solution is the best, specially because it is consistent with what we already do in other places
  - there are some details, uploads are associated with auth keys, so it is tricky to know what keys to associate to. If we make auth keys copying mandatory, we can just associate to the key copy
- identity validation of the user who wants to do the migration. This is the most complex part. The solutions I could thing of at the moment is to rely on auth keys - ask user do create an auth key in new user, but then it would be difficult to have a safe way of key exchange between user and admin, unless user could perform the migration themselves. Thinking about having a migration menu in the website where old user would paste auth key of new user to be used for the account migration. This way, it would not be controlled by admin (and should it? Maybe we don't want to involve admin at all, just give admin the power to revert this action if needed). 
  - There is still the edge case that user lost access to an account. But, this will make identity validation really tricky. So, I would prefer to not include this use case as part of this migration, but we can write things in a way that this use case case could easily be performed by admin in the future.

Thoughts?

**Comment by yusefnapora** [comment]
Reading through the code, it looks like auth keys do get blocked, but the blocking happens based on the `id` of the auth key. So, if we copy the keys, they'll have new `id`s and shouldn't be blocked.
