### ISSUE TITLE
NFT - UP stops uploading 

### ISSUE THREAD

**Issue by mGonzim** [nftstorage/nft.storage#1998]
I am hoping someone can help,

I am uploading using NFT-UP and for some reason my upload stops. The folder I am trying to upload is 23GB large and contains 10k files. The most I was able to upload was 21GB before it stops. To confirm that in fact it does stop my network usage is at 0%.

Any help would be great.

**Comment by jj1980a** [comment]
Same issue here, it gets stuck at around 100 chunks, tried so many times. Do we have any update on this?

**Comment by dchoi27** [comment]
Oh hm - I think this shouldn't be an issue anymore (if the issue is that certain chunks failed to upload, we launched some new infra in production that should have fixed this), but please do reopen if it's still an issue.

If it still an issue, please check to see if this is an issue that's specific to certain pieces of data you're trying to upload - i.e. NFT Up works for other uploads - and if so, putting that data in some sort of file sharing system and allowing us to test with that data would be really helpful.
