### ISSUE TITLE
Pin Status: Failed

### ISSUE THREAD

**Issue by TINLOKSEK** [nftstorage/nft.storage#2048]
After the file is uploaded, I can view the image of the URL, but the status display fails. Do I need to upload the image again?

**Comment by dchoi27** [comment]
Likely, yes. What's the CID?

**Comment by TINLOKSEK** [comment]
This is my CID.
And I tried to re-upload twice, but it still failed, what should I do?

**Comment by TINLOKSEK** [comment]
This is my CID:bafybeidzfxrjplnybfg3etsk5af6qsxmjl3mynv56tlcpr4fib6lc2dn6q
And I tried to re-upload twice, but it still failed, what should I do?

**Comment by dchoi27** [comment]
Looks like your upload is fine - there's some weirdness right now where we have two types of storage infrastructure we need to support because we support remote pinning, and that second type of infrastructure hasn't been able to get all the content (so reported Failed) but is retrying in the background (so eventually should say Pinned). The fact that your data is in Filecoin storage deals now shows that your data is safely available with the other layer of infra though. Sorry for the confusion - we're implementing the pinning API with the primary type of infra now and should be able to remove the "Status" after that.
