### ISSUE TITLE
Uploading NFT on Solana within NFT Storage

### ISSUE THREAD

**Issue by pogotka** [nftstorage/nft.storage#2082]
What is the NFT Storage authentication token? Where I can find it? I'm uploading collection using Sugar

**Comment by yusefnapora** [comment]
By default, metaplex uploads use a custom authentication scheme that doesn't require an authentication token (https://github.com/nftstorage/metaplex-auth). 

This reduces the friction a bit, since people don't need to create an NFT.Storage account. If you want to keep track of your uploads, you can set the `nftStorageKey` field in your [config json](https://docs.metaplex.com/guides/archived/candy-machine-v2/configuration) to an API key for your account.
