### ISSUE TITLE
Uploading NFT images Folder

### ISSUE THREAD

**Issue by sktzbar** [nftstorage/nft.storage#2139]
Hello sir, 

I hope you are doing good. 

while i was trying to upload my collection through NFT storage. as you can see attached. there are number of chunks.

My question is, What are these chunks ? is it like some files are damaged or not uploaded well ?

is it correct to keep uploading the same way ?

Thank you for your support.

![ffgfdfg](https://user-images.githubusercontent.com/111266851/185409577-52bdc8f3-5561-46c7-9112-4b83543b39d3.PNG)

**Comment by gobengo** [comment]
@sktzbar It is most likely because nftup is 'chunking' your bigger upload into smaller chunks that can be uploaded separately. Uploading a small chunk is less error-prone than a big chunk.

Here is where the whole upload gets split into chunks by a splitter.
https://github.com/nftstorage/nft.storage/blob/1e43a31d7a0d9ba96dda50bc492aca7352d42a17/packages/client/src/lib.js#L177
