### ISSUE TITLE
login with Magic sucks

### ISSUE THREAD

**Issue by sterlingcrispin** [nftstorage/nft.storage#2245]
I want to set up an account using a password so that myself and another person can both manage the same set of assets. Only allowing Github and Magic-email-to-sign-in is really a drag

**Comment by unixpi** [comment]
can confirm. endless loop on login after intial sign up

**Comment by vasco-santos** [comment]
Hey folks! This was likely a sporadic issue with the auth service we are currently using. We are working on new flows that take magic link out of the way. Expect updates soon.
For now closing this issue. If you were not able to login again please re-open this and let us know so that we can find a way to unblock you all
