### ISSUE TITLE
Debating my engineer - IPFS fully 100% decentralized?

### ISSUE THREAD

**Issue by JackAttackHIP** [nftstorage/nft.storage#2254]
Full disclosure I am a product manager working with developers to design an implementable decentralized storage system. My engineer claims IPFS are not fully decentralized because ultimately the owner/creator of the IPFS can shut down the network and manipulate the storage at will. Is this true? Is the only way to be 100% decentralized to to contain all of your info on the mainnet limited to 24kb?

Thank you always eager to learn

**Comment by yusefnapora** [comment]
IPFS is designed to be independent of any particular infrastructure provider, but Protocol Labs (the creator of IPFS) does run some infrastructure that would probably cause some availability issues if it were to suddenly disappear. The most "centralizing" pieces are probably the HTTP gateways we run (`ipfs.io` and `dweb.link` being the main ones), as well as the "bootstrap peers" that are used when a new node joins the network, which has a default list hard-coded into libp2p. If all the bootstrap peers were to disappear, new nodes would be unable to join unless manually connected to another peer.

As for manipulating storage, it's not possible for any IPFS node to alter any stored content without changing its hash, which is easily detected on the client. However, if you're requesting content via an HTTP gateway, you need to trust the gateway operator. 

In the interests of full disclosure, if an entity runs enough nodes, they _can_ run an attack to "hide" specific content from other peers, by choosing peer ids "close" to the target content and returning a "not found" response to anyone who asks. So if PL were malicious or compromised, we could theoretically return dishonest content routing results from our nodes. We definitely don't do that, but that's difficult to prove definitively, so you kind of have to take our word for it. Also, to be clear, anyone can run that kind of routing attack; PL is just in a slightly privileged position due to running more nodes than the average IPFS user.

I should also mention that, in the context of off-chain NFT storage, IPFS alone doesn't guarantee that you data will remain available over time. This might be what your engineer is getting at, since you need to depend on someone to keep providing the data to the IPFS network over time. NFT.Storage does this for you, and we also store data in Filecoin, so you'll have a backup in case we ever go away. Filecoin does have availability guarantees, so the storage providers will keep your data even if we disappear. The nice thing about using IPFS is that, if we did ever disappear, you could use another IPFS provider to store the same data without needing to change any of the links to the data, some of which might be impossible to change (e.g. because they're written in an immutable blockchain).

Hope that helps clear things up a bit. LMK if you have more questions :)
