### ISSUE TITLE
Different hash for same file

### ISSUE THREAD

**Issue by wutzebaer** [nftstorage/nft.storage#2259]
When i upload my file at nft.storage i get this bafy hash/link:

https://bafybeigfx7uxbuxodnam4puey3dat5ueq6qehllsdngrunaddeky3tqrnm.ipfs.nftstorage.link/

When i hash it with my local node i get a Qm hash: QmfTDSaSvqL1Zw6KYowPe7G5oNKj1n1Ljtz9UtCGpAWoK9
When i now try to load the Qm hash like this:

https://ipfs.nftstorage.link/ipfs/QmfTDSaSvqL1Zw6KYowPe7G5oNKj1n1Ljtz9UtCGpAWoK9

it does not find the data, only after uploading the file over my local node it can be found, but probably only because i uploaded it and loads the data from my node.

After it is found with the Qm hash it redirects me to a different bafy hash:
https://bafybeih6iuwe6h24ugr2qgkyafk6tti73mxx25am6leirh3fec67bck7jq.ipfs.nftstorage.link/

So why do i get different hashes for the same data, and what can i do, that my File is available with my already present Qm hash?

**Comment by vasco-santos** [comment]
Hi @wutzebaer 

Thanks for reaching out. We default to serve content with subdomain level. This is because of origin isolation that brings nice security benefits like allowing malicious content to be blocked at sub-domain level or hosting content in relative path. You can read more about this at https://docs.ipfs.tech/how-to/address-ipfs-on-web/#dweb-addressing-in-brief

We use CIDv1 by default in web3/nft.storage, but it should be available via the gateway in any of these formats.

In your local node, there is an optional parameter to use CIDv1 as well. You can do:

`ipfs add --cid-version 1 file.txt`

Let me know if you need further help with it

**Comment by wutzebaer** [comment]
Hi @vasco-santos  
thank you for your answer, this helps for future mints, but is there any way to upload my files for already minted nfts which used v0?

**Comment by vasco-santos** [comment]
Hey @wutzebaer 

Not sure I entirely get your question. You should be able to access with v0 kind of path, such as your example https://ipfs.nftstorage.link/ipfs/QmfTDSaSvqL1Zw6KYowPe7G5oNKj1n1Ljtz9UtCGpAWoK9

It will redirect to CIDv1, but it resolves. Anything that I am missing?
