### ISSUE TITLE
upload big file, split car file(over 2gb), Archived status is Pinning

### ISSUE THREAD

**Issue by oceanzhang01** [nftstorage/nft.storage#2274]
upload big file split car file, Archived status is Pinning, if file size less than 2gb, Archived status  is 📌

bafybeiellddlls7kfpcbfk323nrilc6xeottfk3lfywzltx5jh636nn4y4
bafybeihpmwz5y6igkkkwtduaaoidpn34gz5btzgtettirdm2husudnogdm

**Comment by dchoi27** [comment]
- to check if your upload was successful, we have a job that traverses the IPFS graph of the upload to check if all the blocks of data are there. for large uploads, sometimes this job times out, and the status will just say Pinning
- of course, if your upload gives an error or doesn't complete, it probably wasn't successful. so that's the most reliable way
- otherwise, you can spot check individual images / metadata in your uploaded directory from the NFT.Storage gateway to see if the upload was successful. if some of the URLs don't load, it probably wasn't successful.
