### ISSUE TITLE
Long time pending for 48 hours 

### ISSUE THREAD

**Issue by thursday15** [nftstorage/nft.storage#2282]
Hallo NFT.Storage, im submited 5 days ago, but is still pending. you can resolve this?

**Comment by vasco-santos** [comment]
Can you please give us more details of what is pending?

**Comment by dchoi27** [comment]
- to check if your upload was successful, we have a job that traverses the IPFS graph of the upload to check if all the blocks of data are there. for large uploads, sometimes this job times out, and the status will just say Pinning
- of course, if your upload gives an error or doesn't complete, it probably wasn't successful. so that's the most reliable way
- otherwise, you can spot check individual images / metadata in your uploaded directory from the NFT.Storage gateway to see if the upload was successful. if some of the URLs don't load, it probably wasn't successful.
