### ISSUE TITLE
Still Pinning After 36 Hours

### ISSUE THREAD

**Issue by kayes0001** [nftstorage/nft.storage#2296]
I've uploaded my NFT Collection on nft.storage 36 hours ago but its still pinning. The total collection was 21.46GB 10K collection. I haven't uploaded any nfts on nft.storage before so I'm not sure if its normal or not . If its not normal what shall I do to fix this?

**Comment by alanshaw** [comment]
If your collection is unreachable on the network (maybe your node is behind a firewall or NAT?) then IPFS may not be able to retrieve the content. If you can paste the CID we can investigate further. Your best bet right now is to upload directly programmatically or via NFTUp.

**Comment by kayes0001** [comment]
The CID is 
bafybeiaqvq6ck72vd6bxm4te6m66my4f5y3orbryzqfn6vz2fvzqupnhta

Uploaded the folder with NFTUp.

**Comment by ErebusNFT** [comment]
Hey

did it all work out? did you figure out the pinning issue? ?

**Comment by dchoi27** [comment]
- to check if your upload was successful, we have a job that traverses the IPFS graph of the upload to check if all the blocks of data are there. for large uploads, sometimes this job times out, and the status will just say Pinning
- of course, if your upload gives an error or doesn't complete, it probably wasn't successful. so that's the most reliable way
- otherwise, you can spot check individual images / metadata in your uploaded directory from the NFT.Storage gateway to see if the upload was successful. if some of the URLs don't load, it probably wasn't successful.
