### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by ErebusNFT** [nftstorage/nft.storage#2303]
Why im i getting this pinning sign? 
![scrnli_1_26_2023_9-25-38 AM](https://user-images.githubusercontent.com/123290052/214823981-395399bc-96d6-49ad-a2d9-2265d9ac3a2f.png)

**Comment by dchoi27** [comment]
- to check if your upload was successful, we have a job that traverses the IPFS graph of the upload to check if all the blocks of data are there. for large uploads, sometimes this job times out, and the status will just say Pinning
- of course, if your upload gives an error or doesn't complete, it probably wasn't successful. so that's the most reliable way
- otherwise, you can spot check individual images / metadata in your uploaded directory from the NFT.Storage gateway to see if the upload was successful. if some of the URLs don't load, it probably wasn't successful.
