### ISSUE TITLE
What content relations should we we retain in DB ?

### ISSUE THREAD

**Issue by Gozala** [nftstorage/nft.storage#232]
Hi Team,

In the process of redesigning database schema I find myself contemplating following questions:

1. Should directory upload capture relation to all the content (CIDs) that it encloses ?
   - We do retain:
     - File names
      - content types (this one is really questionable as these are inferred by browser and isn't really saved in the the IPFS)
   - However
      - If we encounter CID to enclosed file we would just try to pin it again
      - And we will not be able to skip pinning.
      - And we will not be able to see all the uploads that link to the same file. 
2. Should `/store/` API retain similar links ?
3. What about car uploads ?

On one hand ability to see all the NFTs that link to a specific content and linking it to specific upload seems significant. But on the other hand it does feel like querying IPFS cluster for all the roots that lead to specific content is going to be less error prone and provide more accurate picture.

Would love your input on the matter.

**Comment by Gozala** [comment]
I think ability to recognize that certain upload ended up on the chain is really significant. 
- If upload has not end up on chain it doesn't really qualify as NFT.

However, unless we do capture which CIDs are part of which uploads it is going to be hard to recognize that.

**Comment by alanshaw** [comment]
IMHO we need to continue supporting those fields in nft.storage but I wouldn't do any extra work to link them to database entries at least not just now...

> * If we encounter CID to enclosed file we would just try to pin it again

I think that's ok - we already have the data so it'll be fast. It also registers someone elses interest in keeping that content around.

> * And we will not be able to skip pinning.

Is this essentially the same as the above point or is there some difference I'm missing?

> * And we will not be able to see all the uploads that link to the same file.

I can't think of when we need this - do you have a situation in mind?

> I think ability to recognize that certain upload ended up on the chain is really significant.
> 
>   * If upload has not end up on chain it doesn't really qualify as NFT.
> 
> However, unless we do capture which CIDs are part of which uploads it is going to be hard to recognize that.

If someone uploads a directory then that directory needs to appear on chain. If there is a file that is _in_ a directory where the file _is_ on chain but the directory is not then that's not really good enough because the rest of the directory could contain a large amount of unrelated data.

If someone uploads a file or directory that is referenced via metadata then that's ok - we'll know this from our introspection of the metadata.

**Comment by Gozala** [comment]
> If someone uploads a directory then that directory needs to appear on chain (or be referenced by metadata). If there is a file that is _in_ a directory where the file _is_ on chain but the directory is not then that's not really good enough because the rest of the directory could contain a large amount of unrelated data.

Every single file might be referenced from chain, but directory itself may not be. Which may happen not because user intended to abuse the service but because directory upload provided bulk upload option.
