### ISSUE TITLE
Pinning since 12 days. Pinning service crashed?

### ISSUE THREAD

**Issue by kennybrower** [nftstorage/nft.storage#2321]
I uploaded a bunch of files using the NFTUp app on 2/5/2023.

All files are reachable via IPFS but not pinned according to https://nft.storage/files :

"Archived" state is "Pinning"
"Storage Providers" state is "Queuing"

I monitored the global pinning stats https://nft.storage/stats :
"Total data stored on Filecoin from NFT.Storage" stays at "304.13TB" since last week.

Looks like nothing is being pinned since a week probably longer.

Is this known? Is there an ETA?

**Comment by dchoi27** [comment]
hey - it looks like you have some misconceptions about how the NFT.Storage service works. there is a status alert about delays in getting data into filecoin deals (https://status.nft.storage/) but this does not affect availability of content.

the word "pinned" can mean a lot of different things, but if your content was successfully uploaded to NFT.Storage, then it wouldn't be deleted if it is valid NFT data (we're not running dedicated kubo nodes for users - if someone uploads something then of course it'll be persisted by default).

for your specific case:
- to check if your upload was successful, we have a job that traverses the IPFS graph of the upload to check if all the blocks of data are there. for large uploads, sometimes this job times out, and the status will just say Pinning
- of course, if your upload gives an error or doesn't complete, it probably wasn't successful. so that's the most reliable way
- otherwise, you can spot check individual images / metadata in your uploaded directory from the NFT.Storage gateway to see if the upload was successful. if some of the URLs don't load, it probably wasn't successful.
