### ISSUE TITLE
CMS is giving an error message when trying to save/update a blog post

### ISSUE THREAD

**Issue by damedoteth** [nftstorage/nft.storage#2344]
<img width="331" alt="image" src="https://user-images.githubusercontent.com/110121581/224781621-f99f7865-c181-4910-93a6-37e2bfbe5ea5.png">

**Comment by elizabeth-griffiths** [comment]
Noting we have a blog post that needs to go live around 3pm EST on 14th March.

**Comment by elizabeth-griffiths** [comment]
@damedoteth can you confirm if you've tried on multiple browsers? And are we blocked from posting a new blog article?

**Comment by e-schneid** [comment]
This is likely due to access rights in Johnathon Roach's github account.  A github admin of this repository needs to create a new account (probably with a relevant name, like "nft-storage-blog", but anything works) with write access to nft.storage and then go into the netlify page for blog.nft.storage and update the Github API Access Key to use that new account:

https://user-images.githubusercontent.com/99349687/226979765-a943c98c-72a8-4637-bf98-48fda7cb92d0.png

cc @dchoi27

**Comment by elizabeth-griffiths** [comment]
We’re closing this ticket for now, please re-open if it’s still an issue.
