### ISSUE TITLE
Adding a custom name to uploaded files and metadata

### ISSUE THREAD

**Issue by jaca420** [nftstorage/nft.storage#2489]
Nothing to complain about, but I will start a project where I will upload three or four sets of images and metadata. It would be really great if I can add a custom name for each just to better organize everything ... for example: Metadata Animals and Images Animals ... :))

**Comment by elizabeth-griffiths** [comment]
To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. New account registrations will no longer be accepted for:
The original NFT.Storage web app, API, and SDK
NFTUp
Pinning API

Because of this, we will not be prioritising this request. We'd be keen to hear your feedback on the new version of NFT.Storage though. Check it out at NFT.Storage!
