### ISSUE TITLE
client: Update to stable ipfs-car version (1.x)

### ISSUE THREAD

**Issue by jd1900** [nftstorage/nft.storage#2500]
Current required ipfs-car version (https://github.com/web3-storage/ipfs-car) is "ipfs-car": "^0.6.2", while current stable version is 1.2.0.

We'd love it to be updated to the latest stable version "ipfs-car" version.

**Comment by tuler** [comment]
This is a must for applications which use `ipfs-car` or `@ipld/car` directly since the version used by this package is incompatible with the latest versions of those.

**Comment by elizabeth-griffiths** [comment]
To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. New account registrations will no longer be accepted for:
The original NFT.Storage web app, API, and SDK
NFTUp
Pinning API

Because we will not be allowing uploads beyond 30 June 2024, we don't plan to make any additional upgrades.
