### ISSUE TITLE
Can't login in https://classic.nft.storage/

### ISSUE THREAD

**Issue by starkiiiii** [nftstorage/nft.storage#2596]
Hi I cant login in https://classic.nft.storage/ .
I need API key because I use the app and I get [API Key is malformed or failed to parse].
I have to login in https://classic.nft.storage/ but the site redirecting me into login window after I conform email.
And I didn't register before April 2024.
Thank you for your time.

**Comment by blackicon-eth** [comment]
It looks like they are dismissing the old site. I wanted to upload some NFTs metadata through the new one but I receive the same error (API Key is malformed or failed to parse).
I was wondering if there's an ETA for the new SDK.

**Comment by elizabeth-griffiths** [comment]
@starkiiiii You're correct, since you did not register for  https://classic.nft.storage/  before April 2024 there is no way to get an API key. 
@blackicon-eth 
NFT.Storage is a public good designed to preserve NFT data in decentralized, verifiable Filecoin storage. Aimed at ensuring every NFT remains accessible, we provide a low-cost, one-time fee solution for long-term preservation, aiming to seamlessly integrate across all NFT minting platforms and marketplaces.The cost to store your digital assets on NFT.Storage is USD $2.99 per GB. This is a one-time fee that aims to ensure your NFT data is preserved.

Pinning is separate now. For a more frequent retrieval of the CID including pinning providers, we [recommend considering one of these options](https://nft.storage/blog/onboard-nft-data-to-ipfs).
