### ISSUE TITLE
How to get before data in the UI? What is happening to my production key?

### ISSUE THREAD

**Issue by KishiTheMechanic** [nftstorage/nft.storage#2602]
The new UI is so confusing.

My previous key is still living?
I'm using it on production and seems working fine but I can't find the information anymore.

When the key will be expired?
And there is the new way to use?

Sorry this things are difficult to catch up, please tell me what is happening and what I should do to continue with it.

Thank you always.

Have a great day.

Best regards,
Shota Kishi

**Comment by elizabeth-griffiths** [comment]
Hi Shota,

Since our inception in April 2021, NFT.Storage has become a trusted public good for NFTs, with over 660 TB of data uploaded by our vibrant community. We're excited to share the next phase of NFT.Storage, a natural progression built on our foundational work. We're introducing an evolved NFT.Storage platform alongside the newly formed NFT.Storage DAO, marking a significant step towards enhancing community engagement and paving the way for a sustainable future in NFT preservation.

What’s Changing:
To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. New account registrations will no longer be accepted for:

- The original NFT.Storage web app, API, and SDK
- NFTUp
- Pinning API

Your benefits as an existing account holder:

- Continue to upload off-chain NFT data using the current products through 30 June 2024, at 5 PM EST
- Maintain access to your links through the NFT.Storage Gateway at https://nftstorage.link/ipfs/{CID} 
- All NFT data you’ve already uploaded and will upload before 30 June 2024, will continue to be safely stored and accessible via IPFS and in the Filecoin Network's long-term storage, though over time latency and availability may degrade.

Planning for the Transition:

- This transition is a crucial step towards reinforcing NFT.Storage as a public good, aiming to ensure we can continue to provide a sustainable service. Starting now:
- We're here to assist you in finding the best decentralized IPFS upload solution for your needs. Check our resources below for guidance
- Consider adding additional IPFS hosts to mirror your content from NFT.Storage for improved performance
- Bookmark classic.nft.storage for continued access to upload NFT data to the original platform


Helpful Resources:

- [Read our blog our exploring IPFS upload options](https://nft.storage/blog/onboard-nft-data-to-ipfs)
- [Learn more about the Future of NFT.Storage](https://nft.storage/blog/the-next-chapter-of-nftstorage)
- [Bookmark the link to access the original NFT.Storage web app](https://classic.nft.storage/login/)

Here is information about the new version of NFT.Storage: 
NFT.Storage: Preservation uploader web app and API
Our premier product focuses on the enduring preservation of NFTs, aiming to provide a long-term and cost-effective solution. With a modest one-time fee per GB of storage, payable via fiat and soon through ERC20 tokens, we leverage Filecoin's decentralized storage network, underpinned by an on-chain endowment. This aims to ensure your NFTs remain protected and identifiable, adaptable to future digital shifts. Our service accommodates NFTs across major blockchains, delivering verifiable and long-lasting storage. Should any content become temporarily inaccessible, the NFT data is always available to retrieve from the Filecoin Network..

Complementing our core service, we're enhancing data retrieval from NFT.Storage through collaboration with our Storage Providers to facilitate access via ipfs.io, an IPFS public gateway. While this is currently under development to support efficient data retrieval, we educate users on how to optimally retrieve their stored NFT data from the Filecoin network, tailored to specific use cases. Beyond paying a pinning service to ensure that your images stay pinned to IPFS,  we educate users on direct Filecoin retrieval methods through innovative solutions like Boost and Lassie. Although currently complimentary, future iterations of these retrieval services may introduce fees to maintain high efficiency and access for users.

We're committed to ensuring a great developer experience, offering a user-friendly web app, API, and in the future an SDK for seamless integration and storage management. Looking ahead, our ambition is to integrate NFT.Storage as foundational primitives directly within protocols, layer-, layer-2s and smart contracts. This forward-thinking approach aims to embed NFT storage at the deepest layer of the tech stack, ensuring that our solutions pave the way for mass adoption of digital asset preservation.

NFT Token Checker 
In 2024 the team plans to launch the NFT Token Checker, which serves as an essential tool for marketplaces, wallets, and creators, offering verification of NFT collections, tokens, and CIDs stored by NFT.Storage. This service provides creators and their customers with confidence in the lasting storage of NFTs by displaying a distinct icon on marketplace pages, indicating the NFT is preserved by NFT.Storage. Furthermore, the Token Checker will be fully integrated on the NFT.Storage website, facilitating easy verification of NFT storage status by anyone.

Our vision is to ultimately integrate the NFT Token Checker with block explorers, enhancing the trust and recognition of NFT.Storage across the NFT community.
