### ISSUE TITLE
Error: storing files: API Key is malformed or failed to parse.

### ISSUE THREAD

**Issue by thomxwolfe** [nftstorage/nft.storage#2605]
I get the message: Error: storing files: API Key is malformed or failed to parse. I bought 1 GB of space. I'm trying to upload json files.

**Comment by elizabeth-griffiths** [comment]
"API Key is malformed or failed to parse" is because
an API key from https://app.nft.storage/login
Is being used for
https://classic.nft.storage/ (the API, SDK or NFTUp).
API keys from https://app.nft.storage/login only work with https://app.nft.storage/login.

---
To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. New account registrations will no longer be accepted for:
The original NFT.Storage web app at classic.nft.storage, API, and SDK
NFTUp
Pinning API

If you do not have a classic.nft.storage account, you can use the new version of the product at https://app.nft.storage/.

**Comment by thomxwolfe** [comment]
Hi.

Got the API working, but the json metadata is not showing up on opensea.
The metadata CID (BaseURI) is
bafybeifyu5lozbkegd25pzwx5sflje6f2vlqhlwu4inzdyo3gtguou26ry,
the image CID is bafybeiegenrhwh54seglxmwjwfg5jih6x46dvustdlevtzi4nzi4wplxcq,
the contract address (on base) is
0xa121Da805A8B40b58CB765F167B0C6167163D13D. I get response through pinata's
ipfs viewer, but opensea says that they get a connection service fail
through ipfs.oi.
[image: image.png]

**Comment by elizabeth-griffiths** [comment]
It's best to reach out to opensea about this issue. Thanks!
