### ISSUE TITLE
Buba

### ISSUE THREAD

**Issue by Bubakara49** [nftstorage/nft.storage#2613]
My account has been blocked why?
My ID 105.112.193.185
MY IP 87d65414cc19534b

**Comment by Yiraxa938** [comment]
Which of your account is blocked?

**Comment by elizabeth-griffiths** [comment]
We haven't blocked any accounts in the last few days. 
Are you trying to log in at classic.nft.storage or app.nft.storage? 

Github shows that this github account was created 4 days ago. Please share here or email support @ nft.storage with your login email address or github ID so that we can investigate further

**Comment by elizabeth-griffiths** [comment]
I'm going to close this since we haven't heard back yet. If this is still an issue please re-open the ticket.
