### ISSUE TITLE
Error: storing files: API Key is malformed or failed to parse.

### ISSUE THREAD

**Issue by ic3IT** [nftstorage/nft.storage#2628]
Upon uploading, i keep getting this error. created several new API keys without succes, Also purchased the storage needed.

**Comment by arenkis** [comment]
I am getting the same error.

**Comment by headhunt3r** [comment]
me too

**Comment by elizabeth-griffiths** [comment]
API Key is malformed or failed to parse" is because
an API key from https://app.nft.storage/login
Is being used for
https://classic.nft.storage/ (the API, SDK or NFTUp).
API keys from https://app.nft.storage/login only work with https://app.nft.storage/login.

If you've purchased storage, it can be used to store data in the same login where you purchased it—app.nft.storage.
First mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, here's a blog on how to do that: https://nft.storage/blog/onboard-nft-data-to-ipfs
