### ISSUE TITLE
Using NFT UP 1.0.2.0

### ISSUE THREAD

**Issue by Kevooters** [nftstorage/nft.storage#2629]
I get the following error when using this app. 
Error: storing files: API Key is malformed or failed to parse.

I have tried 2 API keys with no success.

**Comment by headhunt3r** [comment]
same here

**Comment by stevecrosby** [comment]
Same problem. Trying to use it with Bueno

**Comment by Kevooters** [comment]
Signed up and paid for a product that is not offered to new users. Please remedy.

**Comment by elizabeth-griffiths** [comment]
"API Key is malformed or failed to parse" is because
an API key from https://app.nft.storage/login
Is being used for
https://classic.nft.storage/ (the API, SDK or NFTUp).
API keys from https://app.nft.storage/login only work with https://app.nft.storage/login.

If you've purchased storage, it can be used to store data in the same login where you purchased it—app.nft.storage.
First mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, here's a blog on how to do that: https://nft.storage/blog/onboard-nft-data-to-ipfs
