### ISSUE TITLE
api key not work

### ISSUE THREAD

**Issue by PixelsVIP** [nftstorage/nft.storage#2634]
ive put my images in the softwere and than its asks me for API key which i put and also bought 1GB storage [my files are 120 MB]
and it says "API Key is malformed or failed to parse."

**Comment by elizabeth-griffiths** [comment]
"API Key is malformed or failed to parse" is because
an API key from https://app.nft.storage/login
Is being used for
https://classic.nft.storage/ (the API, SDK or NFTUp).
API keys from https://app.nft.storage/login only work with https://app.nft.storage/login.

If you've purchased storage, it can be used to store data in the same login where you purchased it—app.nft.storage.
First mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, here's a blog on how to do that: https://nft.storage/blog/onboard-nft-data-to-ipfs
