### ISSUE TITLE
API Key not working

### ISSUE THREAD

**Issue by Ethereal1990** [nftstorage/nft.storage#2658]
Hi, I got an API Key and bought storage last night. But the key is not working when I tried to create my collection on Stargaze.

![NFT Storage API Key error](https://github.com/nftstorage/nft.storage/assets/171224627/272215f7-31b4-485b-b2cd-ced5596a7fd5)

**Comment by 1028493903** [comment]
Me too

**Comment by 1028493903** [comment]
Are you fix that?

**Comment by pandaamx** [comment]
same here

**Comment by elizabeth-griffiths** [comment]
"API Key is malformed or failed to parse" is because
an API key from https://app.nft.storage/login
Is being used for
https://classic.nft.storage/ (the API, SDK or NFTUp).
API keys from https://app.nft.storage/login only work with https://app.nft.storage/login.
If you've purchased storage, it can be used to store data in the same login where you purchased it—app.nft.storage.
First mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, here's a blog on how to do that: https://nft.storage/blog/onboard-nft-data-to-ipfs
