### ISSUE TITLE
NFT UP API Key malfunction

### ISSUE THREAD

**Issue by AndreiCristianLupu** [nftstorage/nft.storage#2695]
![image](https://github.com/nftstorage/nft.storage/assets/27947250/3a939849-686a-4843-ad4c-a5f10c95a25f)
used this with several API Keys. none is working.

I created my account today on NFT.Storage

NFT UP Doesn't work. What can I do?

**Comment by elizabeth-griffiths** [comment]
"API Key is malformed or failed to parse" is because
an API key from https://app.nft.storage/login
Is being used for
https://classic.nft.storage/ (the API, SDK or NFTUp).
API keys from https://app.nft.storage/login only work with https://app.nft.storage/login.

The original NFT.Storage product (now called NFT.Storage Classic) includes NFTUp. 
To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. New account registrations will no longer be accepted for:
The original NFT.Storage web app, API, and SDK
NFTUp
Pinning API

If you already have a classic.nft.storage account, get an API key from that login and download NFTUp here: https://github.com/nftstorage/nftup. Uploads to NFTUp are free.

If you do not have a classic.nft.storage account, you can use the new version of the product at https://app.nft.storage/.
For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse
