### ISSUE TITLE
Says Invalid token when 

### ISSUE THREAD

**Issue by Sanmit498** [nftstorage/nft.storage#2713]
apple@Apples-MacBook-Air nft_storage_test % node validate_token.mjs

The token is invalid.
Response status: 401
Response text: {"ok":false,"error":{"code":"ERROR_MALFORMED_TOKEN","message":"API Key is malformed or failed to parse."}}

on authorisation : 
const validateToken = async () => {
    const response = await fetch('https://api.nft.storage', {
        headers: {
            'Authorization': `Bearer ${token}`
        }
    });

**Comment by elizabeth-griffiths** [comment]
"API Key is malformed or failed to parse" is because
an API key from https://app.nft.storage/login
Is being used for
https://classic.nft.storage/ (the API, SDK or NFTUp).
API keys from https://app.nft.storage/login only work with https://app.nft.storage/login.

Here is the latest information regarding NFT.Storage Classic, including NFTUp, and your data. As of 30 June 2024, no new uploads to the Classic product (including NFTUp) will be accepted but if you have used the products before your data is safe. Your data is safely stored and accessible via the NFT.Storage Gateway and in decentralized long-term storage in the Filecoin Network. However, over time, latency and availability may degrade.

Check out the new version of NFT.Storage. For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse
