### ISSUE TITLE
CIDs of uploaded files can't be retrieved with any API call

### ISSUE THREAD

**Issue by husnain-chakor** [nftstorage/nft.storage#2720]
Hello, I am currently using the NFT.Storage APIs for managing NFT collections and tokens. The documentation provides comprehensive details on creating collections, adding tokens, and other functionalities. However, I am unable to find any information regarding the retrieval of CIDs (Content Identifiers) for the files uploaded to the service.
Could you please clarify if there is a way to obtain the CIDs for files uploaded via the NFT.Storage API? Specifically, I am looking to understand if the CIDs are included in any response from the upload or token addition endpoints.

**Comment by elizabeth-griffiths** [comment]
Hi @husnain-chakor - thanks for reaching out. We're working on improving documentation around retrieval as we speak. 

From our FAQ page [here](https://nft.storage/faq): 
We're enhancing data retrieval from NFT.Storage through collaboration with our Storage Providers to facilitate access via ipfs.io, a part of the decentralized IPFS network. This IPFS public gateway is currently under development to support efficient data retrieval. In the meantime, it's accessible for experimental use at ipfs.io/[enter CID].

For less frequent retrievals, get your content directly from the Filecoin storage provider. [Learn more about retrieving from Storage Providers](https://app.nft.storage/v1/docs/intro).

For more consistent, day-to-day retrieval needs, the IPFS.io gateway may not be suitable due to the varying reliability of this gateway. For a more suitable frequent retrieval use case, we [recommend considering one of these options](https://nft.storage/blog/onboard-nft-data-to-ipfs).

--
Please give ipfs.io/[enter CID] a try and let us know how it works for you.

**Comment by husnain-chakor** [comment]
Thanks for your response, I'll try the IPFS.io gateway and see if it works for me.

**Comment by elizabeth-griffiths** [comment]
Great! How did it work out?

**Comment by elizabeth-griffiths** [comment]
Bumping this up

**Comment by husnain-chakor** [comment]
So, it didn't work out for me. But i have left it for now and will wait for your documentation update.

**Comment by husnain-chakor** [comment]
So, it didn't work out for me. But i have left it for now and will wait for your documentation update.
