### ISSUE TITLE
Metaplex Sugar CLI Tool showing "Invalid authentication token"

### ISSUE THREAD

**Issue by Buff-Doge-Coin** [nftstorage/nft.storage#2722]
Hello, I am launching an nft collection on Solana network using Metaplex Sugar CLI tool and I'm using nft.storage to upload the nft files. So while running the cli tool it asks me to paste a nft.storage api key, which I did from the newer version of the nft.storage but it's showing the auth token is invalid. How can I fix this issue? Can anyone help me?

**Comment by elizabeth-griffiths** [comment]
Hi - Can you please tell me what documentation you're looking at? The description about NFT.Storage needs to be updated. 

The original NFT.Storage product (now called NFT.Storage Classic) includes NFTUp. 
To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. 

If you do not have a classic.nft.storage account, you can use the new version of the product at https://app.nft.storage/.
For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We preserve these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse

"API Key is malformed or failed to parse" is because
an API key from https://app.nft.storage/login
Is being used for
https://classic.nft.storage/ (the API, SDK or NFTUp).
API keys from https://app.nft.storage/login only work with https://app.nft.storage/login.

**Comment by elizabeth-griffiths** [comment]
Bumping this up

**Comment by elizabeth-griffiths** [comment]
Friendly bump

**Comment by elizabeth-griffiths** [comment]
Closing this as we have not heard
