### ISSUE TITLE
NFT-Up not working: "Error: storing files: API key is malformed or failed to parse."

### ISSUE THREAD

**Issue by noahpred** [nftstorage/nft.storage#2723]
Hi there,

Trying to use NFT-Up.

1. I purchased ample storage from NFT Storage.
2. I created an NFT Storage API key.
3. I pasted the API key into NFT Up when prompted.
4. I drop a file to upload.
5. No matter what sort of file I attempt to upload, I get the following error: "Error: storing files: API key is malformed or failed to parse."

<img width="866" alt="Screenshot 2024-07-17 at 10 47 04" src="https://github.com/user-attachments/assets/85d9cabf-2e81-4e4a-ae99-fdaff1164575">

Can someone please help me resolve this issue? Thanks.
```[tasklist]
### Tasks
```

**Comment by noahpred** [comment]
FWIW, I have already tried the Clear API Token from the Tools menu and then re-entering it and also creating new API keys multiple times to no avail.

Perplexingly, when I click the “(or click to choose)” to select a file, every single file type is greyed out/unavailable.

I'm on macOS 14.5

**Comment by elizabeth-griffiths** [comment]
"API Key is malformed or failed to parse" is because

an API key from https://app.nft.storage/login
Is being used for
https://classic.nft.storage/ (the API, SDK or NFTUp).

API keys from https://app.nft.storage/login only work with https://app.nft.storage/login.

Also, The original NFT.Storage product (now called NFT.Storage Classic) includes NFTUp. 
To align our services more closely with our community's needs and ensure the sustainability of our model, we're updating our service offerings. We'll continue to offer the current product under the name NFT.Storage Classic for existing uploads prior to 30 June 2024 , but no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. New account registrations will no longer be accepted for:

The original NFT.Storage web app, API, and SDK

NFTUp

Pinning API


If you already have a classic.nft.storage account, get an API key from that login and download NFTUp here: https://github.com/nftstorage/nftup. Uploads to NFTUp are free.


If you do not have a classic.nft.storage account, you can use the new version of the product at https://app.nft.storage/.


For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 

https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse

**Comment by noahpred** [comment]
Thanks for getting back to me on this Elizabeth.

Seeing as how I will be unable to use your service as it no longer offers the functionality I need, I must request a full refund for the fully unused storage I purchased yesterday.

All the best,

Noah Pred

**Comment by elizabeth-griffiths** [comment]
Please email support@nft.storage with any refund requests.

**Comment by SentinelAgentAI** [comment]
So I have just paid for the $2.99 storage and downloaded the NFT UP, and I get the same issues. What do I need to do to get this to work? I cannot mint the NFT's first, as I need the IPFS link first?

**Comment by noahpred** [comment]
I personally had better luck with: https://www.lighthouse.storage

**Comment by SentinelAgentAI** [comment]
Thanks I'll check them out

**Comment by diamondly777** [comment]
I get the api_key from nft.storage, not classic.nft.storage. But this code occurs bug as follows.
    const client = new NFTStorage({ token: API_KEY });
uploadFile.tsx:27 
 POST https://api.nft.storage/upload/ 401 (Unauthorized)
await in storeBlob		
uploadToNFTStorage	@	uploadFile.tsx:27
onClick	@	uploadFile.tsx:50

uploadFile.tsx:31 Upload failed: Error: API Key is malformed or failed to parse.
    at cid.retries (nft__storage.js?v=f902799b:9651:23)
    at async RetryOperation._fn (nft__storage.js?v=f902799b:306:19)
uploadToNFTStorage	@	uploadFile.tsx:31
await in uploadToNFTStorage		
onClick	@	uploadFile.tsx:50

how to fix code?
