### ISSUE TITLE
Error: storing files: API Key is malformed or failed to parse.

### ISSUE THREAD

**Issue by Akaam-Zain** [nftstorage/nft.storage#2726]
<img width="992" alt="Screenshot 2024-07-20 at 23 37 45" src="https://github.com/user-attachments/assets/9a16eebd-be3c-4ff2-a9d8-58a118749801">

I am trying to upload my NFTs to nft.storage but I keep received this error. I have purchased storage for this and it's worrying that I am unable to use it. Also the browser app does not allow to upload image files. It only accepts .csv which is quite weird. Please help me on this and kindly initiate a refund if it is not possible to help me on this. 

Thanks!

**Comment by elizabeth-griffiths** [comment]
Hi! Thanks for reaching out 

"API Key is malformed or failed to parse" is because
an API key from https://app.nft.storage/login
Is being used for
https://classic.nft.storage/ (the API, SDK or NFTUp).
API keys from https://app.nft.storage/login only work with https://app.nft.storage/login.

The original NFT.Storage product (now called NFT.Storage Classic) includes NFTUp. 
To ensure the sustainability of our model, we're updating our service offerings no new uploads to the Classic product will be accepted as of 30 June 2024 at 5pm EST. The product in your screenshot is NFTUp.

For the new version which you've purchased storage for, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We preserve these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse

**Comment by Akaam-Zain** [comment]
that's insane! Can I get a refund on my purchase then - because I won't be needing 12gb just to store my metadata

**Comment by elizabeth-griffiths** [comment]
Please email ***@***.*** with refund requests.

**Comment by Akaam-Zain** [comment]
I do not see the email address - just *s. I have sent a request to support@nft.storage but have not heard anything yet.

**Comment by elizabeth-griffiths** [comment]
We will be in touch today. Thanks for your patience

**Comment by elizabeth-griffiths** [comment]
That is the correct email address. We have responded to all outstanding support requests. If you did not receive a response, please resend the email and also let me know here. We've been having some deliverability issues, thanks for your patience.

**Comment by Akaam-Zain** [comment]
sure I have forwarded the email again - please check and let me know. Thank you!

**Comment by elizabeth-griffiths** [comment]
My apologies, we have not received your email yet. We are experiencing
email deliver ability issues, thanks for your patience.

Since we are unable to connect via email, I wanted to let you know the
storage that you purchased compliments hot storage solutions such as Pinata
and Lighthouse.Storage, as the new version of NFT.Storage focuses on
preserving the data in long term verifiable storage whereas the others
listed focus on month to month hot storage.

As we're a public good run by a small team, our policy is that storage
isn't refundable, however I'd be happy to explain the value of NFT.Storage
vs hot storage. I would also love to hear your feedback on the product so
that we can improve it in the future.

For the storage you bought, first mint your NFTs then send us the NFT
data—metadata and imagery CIDs, blockchain(s) minted on, contract address
and token IDs. We store these in long term Filecoin storage to preserve
your NFT data. Note that you need to upload the data to IPFS separately, we
recommend using Pinata or Lighthouse with our referral links to support
NFT.Storage:
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse


If you'd like to connect, here's my calendar to book a meeting:
https://calendly.com/elizabeth_griffiths/30min

Many thanks
Elizabeth

**Comment by elizabeth-griffiths** [comment]
Closing this since we are now connecting for a meeting and also in email communication.
