### ISSUE TITLE
JSON Files

### ISSUE THREAD

**Issue by ChitinNature** [nftstorage/nft.storage#2728]
Your docs say that we can add json files, but the uploader doesnt accept it.

I am not a fan of the new way. just saying, used to recommend your site to everyone. 
Now its pay to play. The system doesnt work, and now I have to convert over 10k json files into csv.

**Comment by elizabeth-griffiths** [comment]
Hi,

Thanks for reaching out and for your feedback.

For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We preserve these in long term Filecoin storage. Was it clear to you that you need to upload the data to IPFS separately?

 We recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse

Have you tried using the API instead of the web app?

**Comment by elizabeth-griffiths** [comment]
Friendly bump

**Comment by elizabeth-griffiths** [comment]
Closing issue since we haven't heard back. Please re-open when you're ready to respond.

**Comment by ChitinNature** [comment]
Hey ya, so I can't just upload my json files?

Where would I store my images to get CIDs, do I have to store them else
where now?

We change our images constantly and would need to upload our meta on a
regular basis.

It wasn't too clear, our NFTs were stored on nft storage, and I dont think
I read it right when the boxcame up. Though I thought in your documents it
said it accepted, I then purchased some gigs and wasn't able to.

So I have to store offsite with pinata and then send it in there?
