### ISSUE TITLE
401 Unauthorized error

### ISSUE THREAD

**Issue by KeerthanaBirelli** [nftstorage/nft.storage#2730]
I am working on a sveltekit project and thought of integrating file upload feature in it. I have created an account at nft.storage and followed ntf.storage documentation. When I upload the file I am getting this error of 401 Unauthorized.
![nft_error](https://github.com/user-attachments/assets/8dd662db-6d38-4f50-b752-d0784b538e1c)
I tried even testing the API key ( that I have generated at https://app.nft.storage/ )  by importing curl command in postman still I got the same error:
![postman_output](https://github.com/user-attachments/assets/1c4a7fe3-2ddc-4cb3-8df8-3c1c0f832512)

**Comment by elizabeth-griffiths** [comment]
"API Key is malformed or failed to parse" is because
an API key from https://app.nft.storage/login
Is being used for
https://classic.nft.storage/ (the API, SDK or NFTUp).
API keys from https://app.nft.storage/login only work with https://app.nft.storage/login.

If you've purchased storage, it can be used to store data in the same login where you purchased it—app.nft.storage.
First mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, here's a blog on how to do that: https://nft.storage/blog/onboard-nft-data-to-ipfs
