### ISSUE TITLE
Error: storing files: API Key is malformed or failed to parse

### ISSUE THREAD

**Issue by Bibbleboop** [nftstorage/nft.storage#2737]
Attempting to complete Stellar Side Quest and use NFT.UP to upload an image but cannot proceed as the API is not accepted  "Error: storing files: API Key is malformed or failed to parse". 
Don't really know what I am doing and have paid NFT.Storage fee but don't even know if I needed to. At this stage I don' know if instructions were misleading or user error on my part. 

Not sure how to proceed as I don't know if the help docs relating to uploading tokens was relevant to fix this issue and the following text on APIs didn't seem to mention my error code

**Comment by elizabeth-griffiths** [comment]
"API Key is malformed or failed to parse" is because
an API key from https://app.nft.storage/login
Is being used for
https://classic.nft.storage/ (the API, SDK or NFTUp).
API keys from https://app.nft.storage/login only work with https://app.nft.storage/login.

Here is the latest information regarding NFT.Storage Classic, including NFTUp. As of 30 June 2024, no new uploads to the Classic product (including NFTUp) will be accepted but if you have used the products before your data is safe. Your data is safely stored and accessible via the NFT.Storage Gateway and in decentralized long-term storage in the Filecoin Network. However, over time, latency and availability may degrade.

Check out the new version of NFT.Storage. For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse
