### ISSUE TITLE
Get an error message once I have entered my API key 

### ISSUE THREAD

**Issue by SentinelAgentAI** [nftstorage/nft.storage#2751]
After I have dragged and dropped my images  it says 'packing files', then it say 'storing files', then I get 'Error: storing files: API key is malformed or failed to parse.
No idea how to get arround this, I have paid for 1GB storage and cannot see any options to do anything different?
![nftup error](https://github.com/user-attachments/assets/a0f80856-d8dd-41ac-a583-bfd80db1249b)

**Comment by elizabeth-griffiths** [comment]
Thank you for reaching out, and I'm sorry to hear you're encountering an issue.

The error message typically occurs when an API key from https://app.nft.storage/login is used for our NFT.Storage Classic product, which includes the NFTUp feature (accessible via https://classic.nft.storage/).

Please note that API keys from https://app.nft.storage/login are only compatible with our new version of the product available at that same URL. They do not work with NFT.Storage Classic.

About the NFT.Storage Classic Transition:
NFT.Storage Classic, our original service, will continue to support existing uploads but does not allow new uploads after June 30, 2024. To meet our community's evolving needs, we've launched a new flagship product at https://app.nft.storage/. This platform is where you can back up off-chain NFT data.

Steps to Resolve the Issue:

- Ensure you are using the correct product based on your API key. Use the new platform at https://app.nft.storage/ if you obtained your API key from there.
- If you're using our Classic product, you'll need a Classic-compatible API key, which is no longer provided for new uploads.
- If you're transitioning to the new service, here's a recommended workflow for using the new version:

1. Upload your data to IPFS. We suggest using Pinata or Lighthouse for this process. For a seamless experience, feel free to check out our referral links and special offers:
- Pinata: Trusted in the IPFS ecosystem since 2018. Use our code NFTSTORAGE50 for 50% off your first month.  
Link: https://www.pinata.cloud/nft-storage-pinata
- Lighthouse: Offering lifetime storage. They provide a 30-day free trial on annual plans. 
Link: https://files.lighthouse.storage/?referby=NFTStorage

2. Mint your NFTs and collect the associated data (metadata CIDs, imagery CIDs, contract address, token IDs).
3. IPFS isn't permanent, so this is why you need to back up your off-chain data with NFT.Storage here: https://app.nft.storage/login (this is the storage that you purchased)

If you continue to experience issues or have further questions, feel free to reach out. We're here to help!

Best regards,
Elizabeth
