### ISSUE TITLE
i keep having upload to ipfs error 

### ISSUE THREAD

**Issue by yahia008** [nftstorage/nft.storage#2754]
I've been using the nft.storage package for my AI NFT minting app. However, when I try to mint an NFT, I encounter an error: "File upload failed." I also attempted to upload a CSV file directly through the nft.storage website, but it failed as well. Any guidance on how to resolve this issue would be appreciated.

**Comment by deveshb-am** [comment]
i also want help with this, trying to upload a json but it's not working, says Something went wrong and 400 bad request

**Comment by elizabeth-griffiths** [comment]
Thank you for reaching out, and I'm sorry to hear you're encountering an issue.

Can you please send me a screenshot of the CSV? 

The error message typically occurs when an API key from https://app.nft.storage/login is used for our NFT.Storage Classic product, which includes the NFTUp feature (accessible via https://classic.nft.storage/).

Please note that API keys from https://app.nft.storage/login are only compatible with our new version of the product available at that same URL. They do not work with NFT.Storage Classic.

About the NFT.Storage Classic Transition:
NFT.Storage Classic, our original service, will continue to support existing uploads but does not allow new uploads after June 30, 2024. To meet our community's evolving needs, we've launched a new flagship product at https://app.nft.storage/. This platform is where you can back up off-chain NFT data.

Steps to Resolve the Issue:

- Ensure you are using the correct product based on your API key. Use the new platform at https://app.nft.storage/ if you obtained your API key from there.
- If you're using our Classic product, you'll need a Classic-compatible API key, which is no longer provided for new uploads.
- If you're transitioning to the new service, here's a recommended workflow for using the new version:

1. Upload your data to IPFS. We suggest using Pinata or Lighthouse for this process. For a seamless experience, feel free to check out our referral links and special offers:
- Pinata: Trusted in the IPFS ecosystem since 2018. Use our code NFTSTORAGE50 for 50% off your first month.  
Link: https://www.pinata.cloud/nft-storage-pinata
- Lighthouse: Offering lifetime storage. They provide a 30-day free trial on annual plans. 
Link: https://files.lighthouse.storage/?referby=NFTStorage

2. Mint your NFTs and collect the associated data (metadata CIDs, imagery CIDs, contract address, token IDs).
3. IPFS isn't permanent, so this is why you need to back up your off-chain data with NFT.Storage here: https://app.nft.storage/login (this is the storage that you purchased)

If you continue to experience issues or have further questions, feel free to reach out. We're here to help!

Best regards,
Elizabeth
