### ISSUE TITLE
Unable to Upload PNG and JSON Files After Purchasing Storage

### ISSUE THREAD

**Issue by svitlana82** [nftstorage/nft.storage#2758]
Hi NFT.Storage Support Team,

I recently purchased 1 GB of storage on NFT.Storage to upload my NFT project files. However, I’m encountering an issue where I’m still unable to upload PNG image files and JSON metadata files.

Could you please assist me with the correct process for uploading these file formats to my account? Are there any specific steps or restrictions I need to follow after purchasing additional storage?

Any guidance would be appreciated, as I’d like to use NFT.Storage for my NFT project.

Thank you for your help!

Best regards,
Svitlana Pryhodko

**Comment by elizabeth-griffiths** [comment]
Hi Svitlana,

Thank you for reaching out, and I'm sorry to hear you're encountering an issue with your uploads. I'll clarify the differences between our products and guide you through the correct process.

Understanding the Two Products:
NFT.Storage Classic (accessible at https://classic.nft.storage/): This was our original service, which no longer allows new uploads as of June 30, 2024. It supports existing uploads but is now limited in functionality.

New NFT.Storage Platform (accessible at https://app.nft.storage/): This is our updated service for new projects, including off-chain NFT data backups. API keys from this new platform work exclusively on the new service.

If you’re using the new platform, make sure your API key is from https://app.nft.storage/login and not from the Classic version.

Steps to back up your data:
Since you've purchased 1 GB of storage, you should be able to back up your off chain data with no issue. Here's how to ensure a smooth upload process:
- Upload your data to IPFS. We suggest using Pinata or Lighthouse for this process. For a seamless experience, feel free to check out our referral links and special offers:
- Pinata: Trusted in the IPFS ecosystem since 2018. Use our code NFTSTORAGE50 for 50% off your first month.  
Link: https://www.pinata.cloud/nft-storage-pinata
- Lighthouse: Offering lifetime storage. They provide a 30-day free trial on annual plans. 
Link: https://files.lighthouse.storage/?referby=NFTStorage
- Log in to your account at [https://app.nft.storage/](https://app.nft.storage/login).
- Use the "Upload" feature to upload the csv. There are instructions here on how to structure the csv

If you still encounter issues, let us know the specific error message you're seeing, and we can help troubleshoot further.

Best regards,
Elizabeth
