### ISSUE TITLE
Refund

### ISSUE THREAD

**Issue by WildyPixel** [nftstorage/nft.storage#2762]
I want a refund. This is not the feature I want. It's very different from the old nftstorage. It doesn't work well. I purchased 1GB and didn't use any storage.

**Comment by elizabeth-griffiths** [comment]
The storage that you purchased compliments hot storage solutions such as Pinata and Lighthouse.Storage, as the new version of NFT.Storage focuses on preserving the data in long term verifiable storage whereas the others listed focus on month to month hot storage. 

As we're a public good run by a small team, our policy is that storage isn't refundable, however I'd be happy to explain the value of NFT.Storage vs hot storage. I would also love to hear your feedback on the product so that we can improve it in the future. 

For the storage you bought, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage to preserve your NFT data. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse

**Comment by WildyPixel** [comment]
Hi,

I need a refund for the 1GB of storage I purchased. I haven’t used any of the storage or uploaded any data, so I don't see why I shouldn't be eligible for a refund.

I get that you have a no-refund policy, but policies can’t override legal rights. According to consumer protection laws, I'm entitled to a refund for services that haven't been used. Since I didn’t use the service at all, it doesn’t make sense to deny a refund.

Please issue the refund as soon as possible. I’d like to resolve this quickly and fairly.

Thanks.
