### ISSUE TITLE
Where is my NFTs storage 

### ISSUE THREAD

**Issue by elanasigns** [nftstorage/nft.storage#2767]
Dear Team,
IF you please i add my nfts from alone time at your website 
and you already sent email that u made a Merger wit Pianta and i should  buy Get more storage and i already i bought
i need to know how i can get my old nfts and jsons files ??
could you please advise me 
Best Regards
Ramy Selim

**Comment by Alexahalid** [comment]
@elanasigns  It sounds like you're having trouble accessing your old NFTs and JSON files after a merger with Pianta and purchasing additional storage. I'll have to refer you to the official support live chat with the ticket ID NFT07638
Please see the link below to our dedicated support line:
[NFT Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by elizabeth-griffiths** [comment]
Do not click on that link. It's not from anyone on our team.

**Comment by NFTStorageGithub** [comment]
Hi Ramy,

Thank you for reaching out to us, and we’re glad you’re using NFT.Storage for your digital assets!

First, here’s how to access your stored NFTs  from the classic service: https://classic-app.nft.storage/login/. You can log in here to view and manage the files you previously uploaded.

Now, let’s explain a bit about the storage service you've purchased! At NFT.Storage, we use a combination of IPFS and Filecoin to make sure your off chain NFT day, stay safe, accessible, and preserved for a long time. Imagine it like a very special library that stores your digital files and always keeps them in a secure spot so you can come back and get them whenever you want.

If you bought storage with us, you essentially got a long-term spot for your files—meaning that our system is set up to keep them available without them disappearing. It’s a smart move because with Filecoin’s network and IPFS, we have checks in place to make sure everything stays safe and easy to reach, even if other storage servers go down.

Let us know if you have any more questions or need any more help!

Best regards,
The NFT.Storage Team
