### ISSUE TITLE
getting api authorization error 

### ISSUE THREAD

**Issue by coinpae** [nftstorage/nft.storage#2772]
const uploadToNFTStorage = async (file) => {
        try {
            const storage = new NFTStorage({
                token: process.env.NEXT_PUBLIC_NFT_STORAGE_KEY
            });

            // Convert File to Blob and upload
            const cid = await storage.storeBlob(new Blob([await file.arrayBuffer()]));

            // Check upload status
            const status = await storage.status(cid);
            console.log('Upload status:', status);

            // Construct the IPFS URL
            const url = `https://ipfs.io/ipfs/${cid}`;
            console.log('Upload successful, IPFS URL:', url);

            return url;
        } catch (err) {
            console.error('IPFS upload error details:', err);
            throw new Error("Failed to upload logo to IPFS: " + (err.message || "Unknown error"));
        }
    };

Getting this error: 
 API Key is malformed or failed to parse.

**Comment by elizabeth-griffiths** [comment]
I hope you’re well! I wanted to share some key updates about the
differences between NFT.Storage Classic and our new NFT.Storage Flagship
product, along with tips to help you manage your NFT data seamlessly.

NFT.Storage Classic
NFT.Storage Classic was the original offering, created to provide free
decentralized storage for NFT data on IPFS and Filecoin. As of June 30,
2024, however, NFT.Storage Classic (including NFTUp) no longer accepts new
uploads. If you’ve previously stored data here, your existing files are
still securely stored and accessible through the NFT.Storage Gateway and
decentralized Filecoin storage.

Over time, though, please note that access speed and availability may
gradually degrade. To ensure uninterrupted, fast access, we recommend
copying your data to a secondary hot storage provider, such as Pinata or
Lighthouse. For a step-by-step guide on how to do this, check out our
resource here: Guide to Copying Data to Additional Storage
<https://d5jqXy04.na1.hs-sales-engage.com/Ctc/Y+23284/d5jqXy04/JlF2-6qcW8wLKSR6lZ3pNW7Vp0mH3kMKchVMLCZX50m97dW98VJnB5KyctcN3w5_cydGmqCW7sVvFH8-p_wkW7Xs7sv8XpMYfW933wDY5gSWSmW7vDVwN7bF_4QW8tT7s330lpkZW77FjxQ46YMgWW84d6KC1PBKwCW6T2TS39kXywfW7zhsBB2KqtC-W92bFHT7sXDVdW5673D-5bZ3QlW3HGwf77mmFmJW7yjfhD2TQ_VWW10-yRs6f-k-0W6vXLHh5Y60G6W52Nt51760ZSFW3CTT-b4t12CXW4fkz8v5fdhdKW6-0LgG4BG9TVW247F5h3yZcL4W3JkQ4Z4WNzPzW4f1YGV3TfrJlVWcbZW87kZ0TVWSZs57f5NZXf92Kffz04>
.

NFT.Storage Flagship Product
Our new NFT.Storage Flagship product is designed specifically for long-term
NFT preservation. Here’s how it works:

   1. *Mint and Manage Your NFTs*: Start by minting your NFTs and getting
   the metadata and imagery Content Identifiers (CIDs).
   2. *Send Us Your NFT Details*: Then, send us the data, including
   metadata and imagery CIDs, the blockchain(s) where they’re minted, contract
   addresses, and token IDs. We’ll store this data in decentralized,
   verifiable Filecoin storage for long-term security.

*Note*: With the Flagship product, you’ll need to upload your NFT data to
IPFS first, as our system doesn’t provide direct IPFS upload. We recommend
Pinata or Lighthouse for this step. If you use our referral links for these
services, you’ll also be helping to support NFT.Storage’s mission: Referral
Link
<https://d5jqXy04.na1.hs-sales-engage.com/Ctc/Y+23284/d5jqXy04/JlF2-6qcW8wLKSR6lZ3pQW97GM2_1PbZvNW55t7qQ1kBM4mW8FTQt633xnGcW7kCWGH7p65DHVc_wsV8Ng38lW3RNVlp3wGnkMW1tl07h3XtZNVW8JvDZT7Wy0FGW7B0_HK2kf6ljN3m6NF1_qXb8W2xd_Tt9b8znJW3rS7sy5ZSdhKN8005WKCW5mfW7jChcM3JGbB1W4LGZz92ZHDGxW95NFVb5DqnycW10CZv25qtqgQW7rLpr14FJzcWW20XrP64Dq0QLV1py6x5mh1gDW2M44R670CpJqW7HX9qN8L1Q3BW47wCk8645Z_LW5cQ85Z8xZDBqW6-0PKD2thmn5N1XTYw2f51hhW5-PlzR6LVpMVW2Vj8PY8GLxX3f5cSxhz04>
.

Common API Key Issue
If you’re receiving the error “API Key is malformed or failed to parse,” it
could be because you’re using an API key from app.nft.storage
<https://app.nft.storage/login> for the Classic version (classic.nft.storage).
Keep in mind that API keys from app.nft.storage
<https://app.nft.storage/login> only work with our new Flagship product, so
please ensure you’re using the correct API key for each platform.

Summary

   - *NFT.Storage Classic*: No new uploads are allowed, but your existing
   data is still made available via the NFT.Storage Gateway and stored in the
   Filecoin. network To ensure better accessibility, we suggest copying it to
   another storage provider.
   - *NFT.Storage Flagship*: Focused on long-term, secure storage for NFTs.
   Mint your NFTs, upload the data to IPFS separately, and send us the details
   to store on Filecoin.

Thank you so much for your continued support of NFT.Storage! If you have
any questions about this transition or need assistance, I’m here to help.

Warm regards,
Elizabeth

**Comment by NFTStorageGithub** [comment]
Please re-open this ticket if the problem is not resolved.
