### ISSUE TITLE
Enable users to specify which cid version (Qm vs bafy) for uploads

### ISSUE THREAD

**Issue by jnthnvctr** [nftstorage/nft.storage#387]
The HEN team mentioned that for minting metadata they need to use a separate IPFS node to generate Qm hashes for their metadata.json because of constraints in the number of characters on the contract side. 

It'd be useful potentially to enable users to specify on upload whether they'd like to generate Qm or bafy hashes.

**Comment by Gozala** [comment]
I've put together [this observable](https://observablehq.com/@protocol/example-for-387) that attempts to clarify what is currently possible and what is not.
> To execute you'd need to fork and add `NFT_STORAGE_TOKEN` secret to your profile or just substitute line that accesses it with your access token.

Here is the screenshot 

![image](https://user-images.githubusercontent.com/21236/131919523-7a6045b6-5067-486b-879a-5f12fe24e9d8.png)


Here is the summary

- It is possible to upload `metadata.json` to nft.storage and encode returned CID string into more compact representation.
- Gateways should be able to serve content regardless of CID encoding in the URL.
- To get `Qm...hash` CID needs to V0
- CID V0 implies _DAG-PB_ encoding of content, but small files (< 1mb) will end up in _Raw_ encoding instead.
- CIDs of small files (<1mb) will not convert to CID v0 (ones that start with `Qm...`), because they aren't _DAG-PB_.
- It is still possible to represent such CIDs in more compact encoding via _base58btc_ strings that will be 49chars long.

If 49 chars will satisfy contract character limit constraint, than solution is simply to take cid from nft.storage and encode it as base58btc string. Otherwise things are bit more complicated, if files aren't small _(<1mb)_ CIDs can be encoded as v0 base58btc ( `Qm...hash` style). It is still possible to do it with [`storeCar`](https://ipfs-shipyard.github.io/nft.storage/client/classes/NFTStorage.html#storeCar) API but that is going to involve a lot more code and maybe at that point it would be worth exposing an option to force `dag-pb` instead.

**Comment by Gozala** [comment]
@jnthnvctr do we have any idea on:

1. Can we get someone from HEN team to comment here ? If 49char fits their limit we don't have an issue.
2. If this just HEN team issue or if this is more common ?
   This might help us with decision if we should recommend car based upload or provide some option to allow CIDv0.

Thanks

**Comment by Gozala** [comment]
cc @alanshaw

**Comment by Gozala** [comment]
@crzypatchwork could you please provide some feedback here
