### ISSUE TITLE
Merge overlapping pieces of NFT.Storage and Web3.Storage

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#389]
There's a ton of similar infrastructure between NFT.Storage and Web3.Storage. Making changes + additions often results in double work. It might take some fitting given slight differences in the ways each handles things, but would be great to simplify (e.g. make NFT.Storage a user of the more general Web3.Storage).

**Comment by dchoi27** [comment]
E.g. #390 #391

**Comment by alanshaw** [comment]
+1 The two projects have significant overlap.

* Mitigate the problem of bugs and features implemented in nft.storage and **not** web3.storage and vice versa.
* Remove duplication of effort implementing features/bug fixes from the other project.
* Less code to maintain overall.
* Will enable us to focus more on innovating in NFT space instead of optimizing for storage/retrieval.
* Simplifies dagcargo to working with just one project (web3.storage) not 2.
* Dog fooding - can we build a dweb app (nft.storage) using web3.storage?

**Comment by ribasushi** [comment]
All good, just want to flag:

> Simplifies dagcargo to working with just one project (web3.storage) not 2.

Actually we will want to keep the separation, due to one being pinning-api exposing, and the other not ( there are a number of considerations how/when to retry, how to prioritize, etc )

Also: we currently do not have a way to do "multiple users from a single token" kind of thing, niftysave has the same problem as well. Having everything from nft.storage come from "one user" from cargo's PoV will be... bad.
