### ISSUE TITLE
Make NFT.Storage Grafana track same metrics as Web3.Storage Grafana

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#504]
At the very least - total unique content added to IPFS would be great (this is the 3rd graph in the Web3.Storage Grafana)

**Comment by vasco-santos** [comment]
Created a PR for the main metric asked for in the OP of the issue.

A quick note after talking with Alan. `total unique content added to IPFS` this claim (which we do in web3 storage land) is not really true. We have no way of actually doing that, so this metric is more the total content added to IPFS and not 100% unique. This is because we can have for example uploads with a simple file, or a directory with that file, or even for example different directories with the same LICENCE file. This will all count, as they root CID differ.

Another note: If we want any other metrics, it would be super helpful to create separate issues for each of them, as we can't work on all of them in a same CIC session, but we can do a couple each time.

**Comment by dchoi27** [comment]
Sg thanks - go ahead and close this when your PR is merged!
