### ISSUE TITLE
Navigation links update

### ISSUE THREAD

**Issue by alanshaw** [nftstorage/nft.storage#568]
<img src="https://user-images.githubusercontent.com/152863/136654350-cca22a94-2563-4555-91fd-788adbee3e8c.png" width="50%"/>

**Comment by zebateira** [comment]
👍 for adding the about link.

I'm unsure about adding the login link since it would create more than one way for mobile users to login/logout, but at the same time it would help those users that expect those auth links to be inside the menu.

maybe we should get more insights on this, @atopal @dchoi27 @olizilla ?

**Comment by dchoi27** [comment]
Is there any harm in the redundancy, or is it just two links that point to the same page? If the latter, think it's fine to add login to the menu to flesh it out!

An aside, the "X" box looks kind of big to me on the mobile screen (maybe especially because the NFT.Storage logo looks proportionately small). Can we play around with shrinking it a tad?
