### ISSUE TITLE
Research how to speed up the data gap fill in niftysave

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#618]
From the work on #556 we discovered the folllowing:

There should be a total of 34 million records in niftysave.  We currently have 18.  
We are running a gap fill scrape of blockchain to fill this gap.  ​
We measured current fill script speed this morning, and  its running too slow (would take roughly 1 year to fill gaps).
We need to determine a way to speed this gap filling up. 

Thus, we will spend time investigating ways to speed up the gap fill

- [x]  Implement Batches writes (https://github.com/ipfs-shipyard/nft.storage/pull/621)
- [x]  Create Dataclip to observe progress (see: https://github.com/ipfs-shipyard/nft.storage/issues/618#issuecomment-944804407)

**Comment by Gozala** [comment]
> We measured current fill script speed this morning, and its running too slow (would take roughly 1 year to fill gaps).

How does was this measured ? Estimate seems surprising because previous crawl took a month at most if we consider all the times we had to stop it. Granted it is missing ~50% of nfts, but even than I would expect it take 2x the previous crawl which would be more like 2 month.

**Comment by Gozala** [comment]
I put together a dataclip to provide some numbers https://data.heroku.com/dataclips/cmlmjwvsbiohfczrpzosolgsnkgl

- **missing_nfts** - NFTs that are in in the sub(graph) but not in our db
- **nfts_to_scan** - With an ongoing rescan how many nfts are there to go
- **estimated_mins** - With the current throughput how many minutes it will take to complete a rescan
- **total_nfts** - All the nfts in the sub(graph) as per Oct 15 4:22PM PST
- **rescan_started** - When did niftysave started a rescan
- **mins_elapsed** - Minutes passed since rescan started
- **nfts_indexed** - All the nfts we have in a db.
- **new_nfts_found** - How many new NFTs were found since rescan started.
- **nfts_rescanned** - How many NFTs have been rescanned.
- **speed** - Avarage number of NFTs been rescanned per minute.

**Comment by Gozala** [comment]
From the above I would guess that switch from batched writes to one at a time write had a very negative impact on throughput. Which is why I would suggest trying following:

1. We can switch to batch writes like we do in the code below which will be a trivial change to test
   https://github.com/ipfs-shipyard/nft.storage/blob/7efc57f6313ec698d3c53f0c5bcbf021dc79a3f9/packages/niftysave/src/analyze.js#L324-L341
2. We do however need to test if failing one insert in the batch fails the whole batch or not. If it isn't we'd need some way to rewind cursor. However I think it does all in one commit.


While chances are that postgres is our bottleneck, in which case batching will not help, I highly doubt that. If hasura is rate limiting us, which might be the case, batching should improve our throughput. General network overhead would also be reduced by batching.

As per https://github.com/ipfs-shipyard/nft.storage/issues/618#issuecomment-944624427 we can also time slice to parallelize scan and speed things up even more.

**Comment by the-simian** [comment]
Quick update: not the best resolution (because only some time has elapsed), but the ongoing estimate has gone from 10 to about 4.5 months. It is safe to say the batches alone have made a huge improvement and there's probably more we can do to speed things up as well
