### ISSUE TITLE
Button component in /website triggers accessibility issues

### ISSUE THREAD

**Issue by the-simian** [nftstorage/nft.storage#839]
Discovered while working on issue #838, the remaining accessibility issues are in the header. The root cause is how the button is constructed. My proposal is we take the construction pattern used in the blog (in progress) and the swagger docs, since it does not have this issue and make this the core pattern for button construction.

**Comment by dashcraft** [comment]
I ran axe dev tools, the issue is the relatively positioned button for the header login hologram effect.
https://axe.deque.com/issues/d71db089-0945-468a-b506-ae8053594ed8

This is the new CSS that corrects the issue:
https://github.com/nftstorage/nft.storage/pull/838/files#diff-becf08281a6c408e392af7727401de82afa7f73656dc6eb76ce8493f7b633ebcR130
