### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by ialexander28** [nftstorage/nft.storage#861]
"Use the client in Node.js or the browser:"  -what does this mean? 

"SyntaxError: Cannot use import statement outside a module"  -I keep getting this error

The docs provided don't make sense and I have no ideas how to use this correctly.  Please help if you can.

**Comment by alanshaw** [comment]
> "Use the client in Node.js or the browser:" -what does this mean?

Currently that's slightly incorrect, we're working through an issue that means you can't run it in the browser without bundling it with webpack or similar. There's an example using vite here: https://github.com/nftstorage/nft.storage/tree/main/packages/client/examples/browser/car

> "SyntaxError: Cannot use import statement outside a module" -I keep getting this error

The client uses ESM modules and Node.js assumes CommonJS unless you tell it otherwise. Pick **one** of these two options:

1. Rename your script from `index.js` to `index.mjs`.
1. Use `npm init` to create a new `package.json` file in your project directory and add `"type": "module",` to it.

Now run with `node index.mjs` (or `node index.js`) and that error should be gone.
