### ISSUE TITLE
Generate CARs for large files/directories via streaming and let NFT.Storage accept them

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#980]
One large technical limitation for uploading large files via the API is the client-side generation of CAR files using our current toolset. Generally speaking, users have out of memory and other performance issues when creating large CAR files using ipfs-car + carbites:
- (Web3.Storage) https://github.com/web3-storage/web3.storage/issues/318
- (Web3.Storage) https://github.com/web3-storage/web3.storage/issues/341
- https://github.com/web3-storage/ipfs-car/issues/69

The way Pinata and others handle this is getting users to upload data to a local IPFS node first and remote pinning it to their account, but for various reasons we want to focus on supporting a path to directly upload.

There are a number of issues to make this a possibility, and then subsequently make it useful for users:
- Allow unixfs-importer (to take?) stream: https://github.com/ipfs/js-ipfs-unixfs/issues/186
- (Potentially) Write streaming CAR file generator
- Back-end work to handle any differences in the data it receives (since CAR chunks created via streaming won't have the root CID of the entire file in each CAR, so the service will need to figure out how to handle and/or display this info to users)

@mikeal feel free to edit this to be more precise!
- Expose these changes in the JS client (e.g. add to `store` methods when a large file is uploaded) and other relevant places (e.g., Electron app in #981)

**Comment by Gozala** [comment]
@dchoi27 reading through the linked issues 

> (Web3.Storage)
Example code fails to put a 9GB file web3-storage/web3.storage#318
(Web3.Storage)
too many open files web3-storage/web3.storage#341
Crash on packing web3-storage/ipfs-car#69

From what I can tell based on comments those are caused by yet unknown bugs in the implementation (not necessarily by an API limitation). That said, current API does not provides a good way to manage resource usage. This makes it

1. Hard to figure out where those issues are coming from
2. Impossible for user to control resource usage

What I am hoping to achieve with #186 is design an API in which user can have direct control of how much memory importer can allocate which I believe would significantly reduce a surface for such bugs.


That alone will not however fully address our problems, that is because car file format contains a header with root CIDs, which can not be known for 9GB file until all of it is chunked into blocks Which implies that program either:

a. chunks it up and stores blocks somewhere on disk
b. blocks are uploaded first while root with dag is uploaded later.


#186 aims to support both options, however I think we'd need to do additional work for either of those options.

**Comment by dchoi27** [comment]
Totally, agreed that reducing the surface area is the best thing we can do in this situation. 

@mikeal had talked about enabling CAR generation that wouldn't need to compute the whole CAR in-memory (https://www.notion.so/protocollabs/2021-12-14-Large-file-uploads-review-9d6e4fc7b47548febda713e6b34cc73b) which this issue is supposed to refer to. I think the gist is to create a bunch of smaller CAR files with different root CIDs, but if they were streamed in a known order to our backend, we could potentially recreate original file.

The new API design you refer to sounds like it would be a good first step - though potentially it sounds independent of allowing for streaming import to unixfs-importer? BTW - you linked to an issue (#186) that might be in a different repo, mind updating the link?

**Comment by Gozala** [comment]
@alanshaw @vasco-santos do we currently have a requirement uploading `Treewalk` splitted CARs ? If that is the case it would imply that following option is going to be incompatible

>  b. blocks are uploaded first while root with dag is uploaded later.

If so it also may be worth re-evaluating pros/cons here because for large files it implies two passes over the content and also storing blocks on disk or memory.

**Comment by Gozala** [comment]
From @alanshaw in slack

> Yeah, although as long as the root block is the root cid in every car it’ll still work
> https://github.com/nftstorage/nft.storage/issues/821
